/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/vehicles/Train.glb -o src/components/models/vehicles/Train.tsx -r public/ 
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame, useThree } from '@react-three/fiber'
import { COLORS } from '@/consts/materials'
import { useUserContext } from '@/hooks/UserContext'

type GLTFResult = GLTF & {
  nodes: {
    Plane099: THREE.Mesh
    Plane099_1: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'Train' | 'CubeAction' | 'CubeAction.001' | 'GateAction' | 'GateAction.001'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>


const materials = {
  TrainBody: new THREE.MeshStandardMaterial({
    color: new THREE.Color(COLORS.Base),
    roughness: 1,
  }),

  TrainWindow: new THREE.MeshStandardMaterial({
    color: new THREE.Color(COLORS.Glass),
    roughness: 0.0,
    metalness: 0.1,
  }),

  TrainWindowNight: new THREE.MeshStandardMaterial({
    color: new THREE.Color(COLORS.GlassNight),
    emissive: new THREE.Color(COLORS.GlassNight),
    emissiveIntensity: .5,
    roughness: 0.2,
    metalness: 0,
  }),
};

export function Train(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, animations } = useGLTF('/models/animatedObjects/Train.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  const { scene, gl } = useThree()

  const clipEnterA = useRef(null);
  const clipEnterB = useRef(null);

  const clipExitA = useRef(null);
  const clipExitB = useRef(null);

  const { isNight } = useUserContext();

  const clipPlanes = [
    new THREE.Plane(new THREE.Vector3(0, 0, -1), 50), // Plane untuk ClipEnter 
    new THREE.Plane(new THREE.Vector3(0, 0, 1), 75),// Plane untuk ClipExit

  ];

  useEffect(() => {
    actions['Train.001'].play();


    // Setiap material pada objek kereta harus memiliki clipping planes.
    Object.values(materials).forEach(material => {
      material.clippingPlanes = clipPlanes;
      material.clipIntersection = false; // Anda bisa mengatur ini menjadi false, tergantung pada efek yang diinginkan.
      material.needsUpdate = true;
    });

    // Jika Anda ingin menambahkan PlaneHelper
    // clipEnterA.current = new THREE.PlaneHelper(clipPlanes[0], 100, 0xff0000); //red
    // clipEnterB.current = new THREE.PlaneHelper(clipPlanes[1], 100, 0x0000ff); //blue

    // group.current.add(clipEnterA.current);
    // group.current.add(clipEnterB.current);


    gl.localClippingEnabled = true;

    // Bersihkan efek saat komponen unmount
    return () => {
      Object.values(materials).forEach(material => {
        material.clippingPlanes = null;
        material.clipIntersection = true;
        material.needsUpdate = true;
      });
      group.current.remove(clipEnterA.current);
      group.current.remove(clipEnterB.current);

    }


  }, [actions, materials, clipPlanes, isNight]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Train001" position={[26.793, 0.529, -86.874]} rotation={[-0.001, 0, -0.014]} scale={0.596}>
          <mesh name="Plane099" geometry={nodes.Plane099.geometry} material={materials.TrainBody} />
          <mesh name="Plane099_1" geometry={nodes.Plane099_1.geometry} material={isNight ? materials.TrainWindowNight : materials.TrainWindow} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/animatedObjects/Train.glb')
