/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/streetlights/Streetlights.glb -o src/components/models/streetlights/Streetlights.tsx -s -k -r public/ 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { materials } from '@/consts/materials'
import { useUserContext } from '@/hooks/UserContext'


// Persentase lampu yang akan dinyalakan
const PERCENT_LAMP = 0.08;
const SPOTLIGHT_COLOR = 0xffffe0; // Warna cahaya
const SPOTLIGHT_INTENSITY = 2; // Intensitas cahaya
const SPOTLIGHT_DISTANCE = 10; // Jarak maksimal cahaya
const SPOTLIGHT_ANGLE = Math.PI / 2; // Sudut penyebaran cahaya
const SPOTLIGHT_PENUMBRA = 0.2; // Penumbra, mengatur kelembutan tepi cahaya
const SPOTLIGHT_DECAY = 1; // Seberapa cepat cahaya meredup dengan jarak


type GLTFResult = GLTF & {
    nodes: {
        Plane205: THREE.Mesh
        Plane205_1: THREE.Mesh
        Plane217: THREE.Mesh
        Plane217_1: THREE.Mesh
        Plane220: THREE.Mesh
        Plane220_1: THREE.Mesh
        Plane221: THREE.Mesh
        Plane221_1: THREE.Mesh
        Plane223: THREE.Mesh
        Plane223_1: THREE.Mesh
        Plane288: THREE.Mesh
        Plane288_1: THREE.Mesh
        Plane289: THREE.Mesh
        Plane289_1: THREE.Mesh
        Plane295: THREE.Mesh
        Plane295_1: THREE.Mesh
        Plane324: THREE.Mesh
        Plane324_1: THREE.Mesh
        Plane325: THREE.Mesh
        Plane325_1: THREE.Mesh
        Plane332: THREE.Mesh
        Plane332_1: THREE.Mesh
        Plane333: THREE.Mesh
        Plane333_1: THREE.Mesh
        Plane334: THREE.Mesh
        Plane334_1: THREE.Mesh
        Plane335: THREE.Mesh
        Plane335_1: THREE.Mesh
        Plane338: THREE.Mesh
        Plane338_1: THREE.Mesh
        Plane340: THREE.Mesh
        Plane340_1: THREE.Mesh
        Plane341: THREE.Mesh
        Plane341_1: THREE.Mesh
        Plane342: THREE.Mesh
        Plane342_1: THREE.Mesh
        Plane344: THREE.Mesh
        Plane344_1: THREE.Mesh
        Plane345: THREE.Mesh
        Plane345_1: THREE.Mesh
        Plane346: THREE.Mesh
        Plane346_1: THREE.Mesh
        Plane347: THREE.Mesh
        Plane347_1: THREE.Mesh
        Plane349: THREE.Mesh
        Plane349_1: THREE.Mesh
        Plane350: THREE.Mesh
        Plane350_1: THREE.Mesh
        Plane351: THREE.Mesh
        Plane351_1: THREE.Mesh
        Plane352: THREE.Mesh
        Plane352_1: THREE.Mesh
        Plane353: THREE.Mesh
        Plane353_1: THREE.Mesh
        Plane354: THREE.Mesh
        Plane354_1: THREE.Mesh
        Plane359: THREE.Mesh
        Plane359_1: THREE.Mesh
        Plane360: THREE.Mesh
        Plane360_1: THREE.Mesh
        Plane361: THREE.Mesh
        Plane361_1: THREE.Mesh
        Plane363: THREE.Mesh
        Plane363_1: THREE.Mesh
        Plane364: THREE.Mesh
        Plane364_1: THREE.Mesh
        Plane365: THREE.Mesh
        Plane365_1: THREE.Mesh
        Plane367: THREE.Mesh
        Plane367_1: THREE.Mesh
        Plane370: THREE.Mesh
        Plane370_1: THREE.Mesh
        Plane371: THREE.Mesh
        Plane371_1: THREE.Mesh
        Plane372: THREE.Mesh
        Plane372_1: THREE.Mesh
        Plane373: THREE.Mesh
        Plane373_1: THREE.Mesh
        Plane374: THREE.Mesh
        Plane374_1: THREE.Mesh
        Plane375: THREE.Mesh
        Plane375_1: THREE.Mesh
        Plane376: THREE.Mesh
        Plane376_1: THREE.Mesh
        Plane377: THREE.Mesh
        Plane377_1: THREE.Mesh
        Plane378: THREE.Mesh
        Plane378_1: THREE.Mesh
        Plane379: THREE.Mesh
        Plane379_1: THREE.Mesh
        Plane380: THREE.Mesh
        Plane380_1: THREE.Mesh
        Plane381: THREE.Mesh
        Plane381_1: THREE.Mesh
        Plane384: THREE.Mesh
        Plane384_1: THREE.Mesh
        Plane385: THREE.Mesh
        Plane385_1: THREE.Mesh
        Plane386: THREE.Mesh
        Plane386_1: THREE.Mesh
        Plane387: THREE.Mesh
        Plane387_1: THREE.Mesh
        Plane388: THREE.Mesh
        Plane388_1: THREE.Mesh
        Plane389: THREE.Mesh
        Plane389_1: THREE.Mesh
        Plane390: THREE.Mesh
        Plane390_1: THREE.Mesh
        Plane391: THREE.Mesh
        Plane391_1: THREE.Mesh
        Plane392: THREE.Mesh
        Plane392_1: THREE.Mesh
        Plane393: THREE.Mesh
        Plane393_1: THREE.Mesh
        Plane394: THREE.Mesh
        Plane394_1: THREE.Mesh
        Plane395: THREE.Mesh
        Plane395_1: THREE.Mesh
        Plane396: THREE.Mesh
        Plane396_1: THREE.Mesh
        Plane397: THREE.Mesh
        Plane397_1: THREE.Mesh
        Plane398: THREE.Mesh
        Plane398_1: THREE.Mesh
        Plane399: THREE.Mesh
        Plane399_1: THREE.Mesh
        Plane400: THREE.Mesh
        Plane400_1: THREE.Mesh
        Plane401: THREE.Mesh
        Plane401_1: THREE.Mesh
        Plane402: THREE.Mesh
        Plane402_1: THREE.Mesh
        Plane403: THREE.Mesh
        Plane403_1: THREE.Mesh
        Plane404: THREE.Mesh
        Plane404_1: THREE.Mesh
        Plane405: THREE.Mesh
        Plane405_1: THREE.Mesh
        Plane406: THREE.Mesh
        Plane406_1: THREE.Mesh
        Plane407: THREE.Mesh
        Plane407_1: THREE.Mesh
        Plane408: THREE.Mesh
        Plane408_1: THREE.Mesh
        Plane409: THREE.Mesh
        Plane409_1: THREE.Mesh
        Plane410: THREE.Mesh
        Plane410_1: THREE.Mesh
        Plane411: THREE.Mesh
        Plane411_1: THREE.Mesh
        Plane412: THREE.Mesh
        Plane412_1: THREE.Mesh
        Plane413: THREE.Mesh
        Plane413_1: THREE.Mesh
        Plane414: THREE.Mesh
        Plane414_1: THREE.Mesh
        Plane415: THREE.Mesh
        Plane415_1: THREE.Mesh
        Plane416: THREE.Mesh
        Plane416_1: THREE.Mesh
        Plane417: THREE.Mesh
        Plane417_1: THREE.Mesh
        Plane418: THREE.Mesh
        Plane418_1: THREE.Mesh
        Plane419: THREE.Mesh
        Plane419_1: THREE.Mesh
        Plane420: THREE.Mesh
        Plane420_1: THREE.Mesh
        Plane422: THREE.Mesh
        Plane422_1: THREE.Mesh
        Plane423: THREE.Mesh
        Plane423_1: THREE.Mesh
        Plane424: THREE.Mesh
        Plane424_1: THREE.Mesh
        Plane425: THREE.Mesh
        Plane425_1: THREE.Mesh
        Plane426: THREE.Mesh
        Plane426_1: THREE.Mesh
    }
    materials: {
        Base: THREE.MeshStandardMaterial
        WindowNight: THREE.MeshStandardMaterial
    }
}


type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Streetlights(props: JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF('/models/streetlights/Streetlights.glb') as GLTFResult

    const { isNight, setStreetLightLoaded, streetLightLoaded, quality } = useUserContext()


    const spotlightsRef = useRef([])
    const groupRef = useRef(null);
    // Setup spotlight untuk semua lampu sekali saja
    // Fungsi untuk menambahkan spotlight hanya pada 20% lampu secara acak
    async function addSpotlights() {
        const childGroups = groupRef.current.children;
        const totalLamps = childGroups.length;
        const activeCount = Math.floor(totalLamps * PERCENT_LAMP); // % dari total lampu

        // Memilih indeks acak untuk lampu yang akan diaktifkan
        let activeIndexes = new Set();
        while (activeIndexes.size < activeCount) {
            const randomIndex = Math.floor(Math.random() * totalLamps);
            activeIndexes.add(randomIndex);
        }

        const promises = childGroups.map((childGroup, index) =>
            new Promise((resolve) => {
                if (activeIndexes.has(index)) {
                    const lampMesh = childGroup.children.find((child) => child.name.includes('_1'));
                    if (lampMesh && !spotlightsRef.current[index]) {
                        const spotlight = new THREE.SpotLight(
                            SPOTLIGHT_COLOR,
                            SPOTLIGHT_INTENSITY,
                            SPOTLIGHT_DISTANCE,
                            SPOTLIGHT_ANGLE,
                            SPOTLIGHT_PENUMBRA,
                            SPOTLIGHT_DECAY
                        );
                        spotlight.position.set(lampMesh.position.x + 0.1, lampMesh.position.y + 1, lampMesh.position.z - 0.2);
                        spotlight.target.position.set(lampMesh.position.x, lampMesh.position.y, lampMesh.position.z - 3);
                        spotlight.castShadow = false;
                        childGroup.add(spotlight);
                        childGroup.add(spotlight.target);
                        spotlightsRef.current[index] = spotlight; // Menyimpan spotlight ke dalam ref
                    }
                }
                resolve(undefined);
            })
        );

        await Promise.all(promises);
        setStreetLightLoaded(true); // Memperbarui state ketika semua spotlight selesai dimuat
    }

    // Panggil fungsi async ketika komponen dimount
    useEffect(() => {
        if (groupRef.current && !streetLightLoaded) {

            addSpotlights();
        }
    }, [streetLightLoaded, quality]); // Hanya dijalankan sekali pada saat komponen dimount

    // Kontrol visibilitas spotlight berdasarkan waktu siang atau malam
    useEffect(() => {
        let timeoutId;
        const updateVisibilityAsync = () => {
            spotlightsRef.current.forEach((spotlight) => {
                if (spotlight) {
                    setTimeout(() => {
                        spotlight.visible = isNight;
                        spotlight.target.visible = isNight;
                    }, 0); // Menjalankan pembaruan di next event loop
                }
            });
        };

        updateVisibilityAsync();

        return () => {
            clearTimeout(timeoutId); // Membersihkan timeout saat komponen di-unmount
        };
    }, [isNight]);


    return (
        <group {...props} dispose={null} ref={groupRef}>
            <group name="Stretlight" position={[21.036, 0.549, 9.184]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight008" position={[5.332, 0.549, 4.228]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight012" position={[5.598, 0.549, -11.664]} rotation={[Math.PI, -0.738, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight020" position={[21.293, 0.549, 4.05]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight028" position={[20.946, 0.549, -30.086]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight032" position={[20.933, 0.549, -46.269]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight053" position={[-17.16, 0.549, -62.692]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight057" position={[-21.517, 0.549, -41.1]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight002" position={[-3.029, 0.549, 51.886]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight092" position={[25.386, 0.38, 58.103]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane205" castShadow receiveShadow geometry={nodes.Plane205.geometry} material={materials.Base} />
                <mesh name="Plane205_1" castShadow receiveShadow geometry={nodes.Plane205_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight001" position={[20.93, 0.549, 19.8]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane217" castShadow receiveShadow geometry={nodes.Plane217.geometry} material={materials.Base} />
                <mesh name="Plane217_1" castShadow receiveShadow geometry={nodes.Plane217_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight004" position={[7.202, 0.549, 20.134]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.331}>
                <mesh name="Plane220" castShadow receiveShadow geometry={nodes.Plane220.geometry} material={materials.Base} />
                <mesh name="Plane220_1" castShadow receiveShadow geometry={nodes.Plane220_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight005" position={[-5.741, 0.549, 20.134]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane221" castShadow receiveShadow geometry={nodes.Plane221.geometry} material={materials.Base} />
                <mesh name="Plane221_1" castShadow receiveShadow geometry={nodes.Plane221_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight006" position={[7.727, 0.549, 8.646]} scale={1.331}>
                <mesh name="Plane223" castShadow receiveShadow geometry={nodes.Plane223.geometry} material={materials.Base} />
                <mesh name="Plane223_1" castShadow receiveShadow geometry={nodes.Plane223_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight007" position={[-5.746, 0.549, 9.055]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane288" castShadow receiveShadow geometry={nodes.Plane288.geometry} material={materials.Base} />
                <mesh name="Plane288_1" castShadow receiveShadow geometry={nodes.Plane288_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight009" position={[5.208, 0.549, -6.791]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane289" castShadow receiveShadow geometry={nodes.Plane289.geometry} material={materials.Base} />
                <mesh name="Plane289_1" castShadow receiveShadow geometry={nodes.Plane289_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight010" position={[-5.477, 0.549, 4.249]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane295" castShadow receiveShadow geometry={nodes.Plane295.geometry} material={materials.Base} />
                <mesh name="Plane295_1" castShadow receiveShadow geometry={nodes.Plane295_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight011" position={[-5.583, 0.549, -6.873]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane324" castShadow receiveShadow geometry={nodes.Plane324.geometry} material={materials.Base} />
                <mesh name="Plane324_1" castShadow receiveShadow geometry={nodes.Plane324_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight013" position={[-5.709, 0.549, -11.664]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane325" castShadow receiveShadow geometry={nodes.Plane325.geometry} material={materials.Base} />
                <mesh name="Plane325_1" castShadow receiveShadow geometry={nodes.Plane325_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight014" position={[5.598, 0.549, -41.091]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane332" castShadow receiveShadow geometry={nodes.Plane332.geometry} material={materials.Base} />
                <mesh name="Plane332_1" castShadow receiveShadow geometry={nodes.Plane332_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight015" position={[-5.709, 0.549, -41.108]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane333" castShadow receiveShadow geometry={nodes.Plane333.geometry} material={materials.Base} />
                <mesh name="Plane333_1" castShadow receiveShadow geometry={nodes.Plane333_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight016" position={[5.598, 0.549, -26.076]} rotation={[0, -Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane334" castShadow receiveShadow geometry={nodes.Plane334.geometry} material={materials.Base} />
                <mesh name="Plane334_1" castShadow receiveShadow geometry={nodes.Plane334_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight017" position={[-5.709, 0.549, -26.076]} rotation={[0, Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane335" castShadow receiveShadow geometry={nodes.Plane335.geometry} material={materials.Base} />
                <mesh name="Plane335_1" castShadow receiveShadow geometry={nodes.Plane335_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight021" position={[21.204, 0.549, -25.249]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane338" castShadow receiveShadow geometry={nodes.Plane338.geometry} material={materials.Base} />
                <mesh name="Plane338_1" castShadow receiveShadow geometry={nodes.Plane338_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight023" position={[21.472, 0.549, -11.334]} rotation={[0, -Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane340" castShadow receiveShadow geometry={nodes.Plane340.geometry} material={materials.Base} />
                <mesh name="Plane340_1" castShadow receiveShadow geometry={nodes.Plane340_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight024" position={[9.831, 0.549, 4.05]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane341" castShadow receiveShadow geometry={nodes.Plane341.geometry} material={materials.Base} />
                <mesh name="Plane341_1" castShadow receiveShadow geometry={nodes.Plane341_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight025" position={[9.743, 0.549, -25.249]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane342" castShadow receiveShadow geometry={nodes.Plane342.geometry} material={materials.Base} />
                <mesh name="Plane342_1" castShadow receiveShadow geometry={nodes.Plane342_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight027" position={[9.619, 0.549, -11.334]} rotation={[0, Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane344" castShadow receiveShadow geometry={nodes.Plane344.geometry} material={materials.Base} />
                <mesh name="Plane344_1" castShadow receiveShadow geometry={nodes.Plane344_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight029" position={[20.946, 0.549, -40.92]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane345" castShadow receiveShadow geometry={nodes.Plane345.geometry} material={materials.Base} />
                <mesh name="Plane345_1" castShadow receiveShadow geometry={nodes.Plane345_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight030" position={[9.745, 0.549, -30.086]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane346" castShadow receiveShadow geometry={nodes.Plane346.geometry} material={materials.Base} />
                <mesh name="Plane346_1" castShadow receiveShadow geometry={nodes.Plane346_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight031" position={[9.745, 0.549, -40.92]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane347" castShadow receiveShadow geometry={nodes.Plane347.geometry} material={materials.Base} />
                <mesh name="Plane347_1" castShadow receiveShadow geometry={nodes.Plane347_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight033" position={[20.933, 0.549, -57.266]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane349" castShadow receiveShadow geometry={nodes.Plane349.geometry} material={materials.Base} />
                <mesh name="Plane349_1" castShadow receiveShadow geometry={nodes.Plane349_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight034" position={[20.848, 0.549, -64.568]} rotation={[0, -Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane350" castShadow receiveShadow geometry={nodes.Plane350.geometry} material={materials.Base} />
                <mesh name="Plane350_1" castShadow receiveShadow geometry={nodes.Plane350_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight035" position={[11.403, 0.549, -64.568]} rotation={[0, Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane351" castShadow receiveShadow geometry={nodes.Plane351.geometry} material={materials.Base} />
                <mesh name="Plane351_1" castShadow receiveShadow geometry={nodes.Plane351_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight036" position={[-13.278, 0.549, -64.568]} rotation={[0, Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane352" castShadow receiveShadow geometry={nodes.Plane352.geometry} material={materials.Base} />
                <mesh name="Plane352_1" castShadow receiveShadow geometry={nodes.Plane352_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight037" position={[-21.042, 0.549, -46.269]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane353" castShadow receiveShadow geometry={nodes.Plane353.geometry} material={materials.Base} />
                <mesh name="Plane353_1" castShadow receiveShadow geometry={nodes.Plane353_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight038" position={[-21.042, 0.549, -57.266]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane354" castShadow receiveShadow geometry={nodes.Plane354.geometry} material={materials.Base} />
                <mesh name="Plane354_1" castShadow receiveShadow geometry={nodes.Plane354_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight043" position={[-0.268, 0.549, -46.039]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane359" castShadow receiveShadow geometry={nodes.Plane359.geometry} material={materials.Base} />
                <mesh name="Plane359_1" castShadow receiveShadow geometry={nodes.Plane359_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight044" position={[-0.268, 0.549, -57.723]} scale={1.331}>
                <mesh name="Plane360" castShadow receiveShadow geometry={nodes.Plane360.geometry} material={materials.Base} />
                <mesh name="Plane360_1" castShadow receiveShadow geometry={nodes.Plane360_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight045" position={[20.848, 0.549, -70.338]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane361" castShadow receiveShadow geometry={nodes.Plane361.geometry} material={materials.Base} />
                <mesh name="Plane361_1" castShadow receiveShadow geometry={nodes.Plane361_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight047" position={[2.784, 0.549, -70.338]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane363" castShadow receiveShadow geometry={nodes.Plane363.geometry} material={materials.Base} />
                <mesh name="Plane363_1" castShadow receiveShadow geometry={nodes.Plane363_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight048" position={[-12.212, 0.549, -70.338]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane364" castShadow receiveShadow geometry={nodes.Plane364.geometry} material={materials.Base} />
                <mesh name="Plane364_1" castShadow receiveShadow geometry={nodes.Plane364_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight049" position={[2.947, 0.549, -67.169]} scale={1.331}>
                <mesh name="Plane365" castShadow receiveShadow geometry={nodes.Plane365.geometry} material={materials.Base} />
                <mesh name="Plane365_1" castShadow receiveShadow geometry={nodes.Plane365_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight051" position={[2.947, 0.549, -62.13]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane367" castShadow receiveShadow geometry={nodes.Plane367.geometry} material={materials.Base} />
                <mesh name="Plane367_1" castShadow receiveShadow geometry={nodes.Plane367_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight054" position={[-17.16, 0.549, -68.9]} rotation={[0, -Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane370" castShadow receiveShadow geometry={nodes.Plane370.geometry} material={materials.Base} />
                <mesh name="Plane370_1" castShadow receiveShadow geometry={nodes.Plane370_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight055" position={[-36.841, 0.549, -62.692]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane371" castShadow receiveShadow geometry={nodes.Plane371.geometry} material={materials.Base} />
                <mesh name="Plane371_1" castShadow receiveShadow geometry={nodes.Plane371_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight056" position={[-26.61, 0.549, -62.692]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane372" castShadow receiveShadow geometry={nodes.Plane372.geometry} material={materials.Base} />
                <mesh name="Plane372_1" castShadow receiveShadow geometry={nodes.Plane372_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight058" position={[-21.517, 0.549, -15.931]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane373" castShadow receiveShadow geometry={nodes.Plane373.geometry} material={materials.Base} />
                <mesh name="Plane373_1" castShadow receiveShadow geometry={nodes.Plane373_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight059" position={[-21.517, 0.549, -27.265]} rotation={[0, Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane374" castShadow receiveShadow geometry={nodes.Plane374.geometry} material={materials.Base} />
                <mesh name="Plane374_1" castShadow receiveShadow geometry={nodes.Plane374_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight060" position={[-10.352, 0.549, -41.1]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane375" castShadow receiveShadow geometry={nodes.Plane375.geometry} material={materials.Base} />
                <mesh name="Plane375_1" castShadow receiveShadow geometry={nodes.Plane375_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight061" position={[-10.352, 0.549, -15.931]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane376" castShadow receiveShadow geometry={nodes.Plane376.geometry} material={materials.Base} />
                <mesh name="Plane376_1" castShadow receiveShadow geometry={nodes.Plane376_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight062" position={[-10.121, 0.549, -27.265]} rotation={[0, -Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane377" castShadow receiveShadow geometry={nodes.Plane377.geometry} material={materials.Base} />
                <mesh name="Plane377_1" castShadow receiveShadow geometry={nodes.Plane377_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight063" position={[-21.517, 0.549, -11.61]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane378" castShadow receiveShadow geometry={nodes.Plane378.geometry} material={materials.Base} />
                <mesh name="Plane378_1" castShadow receiveShadow geometry={nodes.Plane378_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight064" position={[-10.352, 0.549, -11.61]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane379" castShadow receiveShadow geometry={nodes.Plane379.geometry} material={materials.Base} />
                <mesh name="Plane379_1" castShadow receiveShadow geometry={nodes.Plane379_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight065" position={[-21.246, 0.549, 20.107]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane380" castShadow receiveShadow geometry={nodes.Plane380.geometry} material={materials.Base} />
                <mesh name="Plane380_1" castShadow receiveShadow geometry={nodes.Plane380_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight066" position={[-10.472, 0.549, 19.987]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane381" castShadow receiveShadow geometry={nodes.Plane381.geometry} material={materials.Base} />
                <mesh name="Plane381_1" castShadow receiveShadow geometry={nodes.Plane381_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight069" position={[-21.517, 0.549, 4.765]} rotation={[0, Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane384" castShadow receiveShadow geometry={nodes.Plane384.geometry} material={materials.Base} />
                <mesh name="Plane384_1" castShadow receiveShadow geometry={nodes.Plane384_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight070" position={[-10.352, 0.549, 4.765]} rotation={[0, -Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane385" castShadow receiveShadow geometry={nodes.Plane385.geometry} material={materials.Base} />
                <mesh name="Plane385_1" castShadow receiveShadow geometry={nodes.Plane385_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight067" position={[-21.227, 0.549, 24.783]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane386" castShadow receiveShadow geometry={nodes.Plane386.geometry} material={materials.Base} />
                <mesh name="Plane386_1" castShadow receiveShadow geometry={nodes.Plane386_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight068" position={[-21.227, 0.549, 35.937]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane387" castShadow receiveShadow geometry={nodes.Plane387.geometry} material={materials.Base} />
                <mesh name="Plane387_1" castShadow receiveShadow geometry={nodes.Plane387_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight071" position={[-7.772, 0.549, 24.783]} scale={1.331}>
                <mesh name="Plane388" castShadow receiveShadow geometry={nodes.Plane388.geometry} material={materials.Base} />
                <mesh name="Plane388_1" castShadow receiveShadow geometry={nodes.Plane388_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight072" position={[-7.772, 0.549, 35.937]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane389" castShadow receiveShadow geometry={nodes.Plane389.geometry} material={materials.Base} />
                <mesh name="Plane389_1" castShadow receiveShadow geometry={nodes.Plane389_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight073" position={[5.173, 0.549, 24.783]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane390" castShadow receiveShadow geometry={nodes.Plane390.geometry} material={materials.Base} />
                <mesh name="Plane390_1" castShadow receiveShadow geometry={nodes.Plane390_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight074" position={[5.173, 0.549, 35.937]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane391" castShadow receiveShadow geometry={nodes.Plane391.geometry} material={materials.Base} />
                <mesh name="Plane391_1" castShadow receiveShadow geometry={nodes.Plane391_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight075" position={[10.012, 0.549, 24.783]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane392" castShadow receiveShadow geometry={nodes.Plane392.geometry} material={materials.Base} />
                <mesh name="Plane392_1" castShadow receiveShadow geometry={nodes.Plane392_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight076" position={[10.012, 0.549, 35.937]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane393" castShadow receiveShadow geometry={nodes.Plane393.geometry} material={materials.Base} />
                <mesh name="Plane393_1" castShadow receiveShadow geometry={nodes.Plane393_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight077" position={[25.173, 0.549, 24.357]} scale={1.331}>
                <mesh name="Plane394" castShadow receiveShadow geometry={nodes.Plane394.geometry} material={materials.Base} />
                <mesh name="Plane394_1" castShadow receiveShadow geometry={nodes.Plane394_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight078" position={[25.356, 0.549, 36.374]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane395" castShadow receiveShadow geometry={nodes.Plane395.geometry} material={materials.Base} />
                <mesh name="Plane395_1" castShadow receiveShadow geometry={nodes.Plane395_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight003" position={[-3.029, 0.549, 40.965]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane396" castShadow receiveShadow geometry={nodes.Plane396.geometry} material={materials.Base} />
                <mesh name="Plane396_1" castShadow receiveShadow geometry={nodes.Plane396_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight018" position={[-21.038, 0.549, 51.886]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane397" castShadow receiveShadow geometry={nodes.Plane397.geometry} material={materials.Base} />
                <mesh name="Plane397_1" castShadow receiveShadow geometry={nodes.Plane397_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight019" position={[-21.038, 0.549, 40.965]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane398" castShadow receiveShadow geometry={nodes.Plane398.geometry} material={materials.Base} />
                <mesh name="Plane398_1" castShadow receiveShadow geometry={nodes.Plane398_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight022" position={[1.321, 0.549, 51.886]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane399" castShadow receiveShadow geometry={nodes.Plane399.geometry} material={materials.Base} />
                <mesh name="Plane399_1" castShadow receiveShadow geometry={nodes.Plane399_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight026" position={[1.321, 0.549, 40.965]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane400" castShadow receiveShadow geometry={nodes.Plane400.geometry} material={materials.Base} />
                <mesh name="Plane400_1" castShadow receiveShadow geometry={nodes.Plane400_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight039" position={[20.982, 0.549, 51.886]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane401" castShadow receiveShadow geometry={nodes.Plane401.geometry} material={materials.Base} />
                <mesh name="Plane401_1" castShadow receiveShadow geometry={nodes.Plane401_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight040" position={[20.982, 0.549, 40.965]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane402" castShadow receiveShadow geometry={nodes.Plane402.geometry} material={materials.Base} />
                <mesh name="Plane402_1" castShadow receiveShadow geometry={nodes.Plane402_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight041" position={[33.963, 0.549, 52.206]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane403" castShadow receiveShadow geometry={nodes.Plane403.geometry} material={materials.Base} />
                <mesh name="Plane403_1" castShadow receiveShadow geometry={nodes.Plane403_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight042" position={[33.643, 0.549, 40.965]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane404" castShadow receiveShadow geometry={nodes.Plane404.geometry} material={materials.Base} />
                <mesh name="Plane404_1" castShadow receiveShadow geometry={nodes.Plane404_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight046" position={[61.447, 0.549, 51.886]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane405" castShadow receiveShadow geometry={nodes.Plane405.geometry} material={materials.Base} />
                <mesh name="Plane405_1" castShadow receiveShadow geometry={nodes.Plane405_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight050" position={[61.242, 0.549, 40.76]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane406" castShadow receiveShadow geometry={nodes.Plane406.geometry} material={materials.Base} />
                <mesh name="Plane406_1" castShadow receiveShadow geometry={nodes.Plane406_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight052" position={[47.038, 0.549, 51.886]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane407" castShadow receiveShadow geometry={nodes.Plane407.geometry} material={materials.Base} />
                <mesh name="Plane407_1" castShadow receiveShadow geometry={nodes.Plane407_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight079" position={[47.038, 0.549, 40.965]} scale={1.331}>
                <mesh name="Plane408" castShadow receiveShadow geometry={nodes.Plane408.geometry} material={materials.Base} />
                <mesh name="Plane408_1" castShadow receiveShadow geometry={nodes.Plane408_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight080" position={[33.643, 0.549, 57.905]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane409" castShadow receiveShadow geometry={nodes.Plane409.geometry} material={materials.Base} />
                <mesh name="Plane409_1" castShadow receiveShadow geometry={nodes.Plane409_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight081" position={[61.447, 0.549, 57.905]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane410" castShadow receiveShadow geometry={nodes.Plane410.geometry} material={materials.Base} />
                <mesh name="Plane410_1" castShadow receiveShadow geometry={nodes.Plane410_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight082" position={[47.038, 0.549, 57.905]} scale={1.331}>
                <mesh name="Plane411" castShadow receiveShadow geometry={nodes.Plane411.geometry} material={materials.Base} />
                <mesh name="Plane411_1" castShadow receiveShadow geometry={nodes.Plane411_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight083" position={[33.643, 0.549, 71.966]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane412" castShadow receiveShadow geometry={nodes.Plane412.geometry} material={materials.Base} />
                <mesh name="Plane412_1" castShadow receiveShadow geometry={nodes.Plane412_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight084" position={[61.447, 0.549, 71.966]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane413" castShadow receiveShadow geometry={nodes.Plane413.geometry} material={materials.Base} />
                <mesh name="Plane413_1" castShadow receiveShadow geometry={nodes.Plane413_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight085" position={[47.038, 0.549, 71.966]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane414" castShadow receiveShadow geometry={nodes.Plane414.geometry} material={materials.Base} />
                <mesh name="Plane414_1" castShadow receiveShadow geometry={nodes.Plane414_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight086" position={[65.841, 0.549, 56.748]} rotation={[0, Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane415" castShadow receiveShadow geometry={nodes.Plane415.geometry} material={materials.Base} />
                <mesh name="Plane415_1" castShadow receiveShadow geometry={nodes.Plane415_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight087" position={[65.841, 0.549, 40.965]} rotation={[0, Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane416" castShadow receiveShadow geometry={nodes.Plane416.geometry} material={materials.Base} />
                <mesh name="Plane416_1" castShadow receiveShadow geometry={nodes.Plane416_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight088" position={[66.174, 0.549, 72.299]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={1.331}>
                <mesh name="Plane417" castShadow receiveShadow geometry={nodes.Plane417.geometry} material={materials.Base} />
                <mesh name="Plane417_1" castShadow receiveShadow geometry={nodes.Plane417_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight089" position={[80.401, 0.549, 56.748]} rotation={[0, -Math.PI / 2, 0]} scale={1.331}>
                <mesh name="Plane418" castShadow receiveShadow geometry={nodes.Plane418.geometry} material={materials.Base} />
                <mesh name="Plane418_1" castShadow receiveShadow geometry={nodes.Plane418_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight090" position={[80.164, 0.549, 40.729]} rotation={[0, -Math.PI / 4, 0]} scale={1.331}>
                <mesh name="Plane419" castShadow receiveShadow geometry={nodes.Plane419.geometry} material={materials.Base} />
                <mesh name="Plane419_1" castShadow receiveShadow geometry={nodes.Plane419_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight091" position={[80.004, 0.549, 72.363]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} scale={1.331}>
                <mesh name="Plane420" castShadow receiveShadow geometry={nodes.Plane420.geometry} material={materials.Base} />
                <mesh name="Plane420_1" castShadow receiveShadow geometry={nodes.Plane420_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight093" position={[15.529, 0.38, 58.103]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane422" castShadow receiveShadow geometry={nodes.Plane422.geometry} material={materials.Base} />
                <mesh name="Plane422_1" castShadow receiveShadow geometry={nodes.Plane422_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight094" position={[1.816, 0.38, 58.103]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane423" castShadow receiveShadow geometry={nodes.Plane423.geometry} material={materials.Base} />
                <mesh name="Plane423_1" castShadow receiveShadow geometry={nodes.Plane423_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight095" position={[-3.853, 0.38, 58.103]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane424" castShadow receiveShadow geometry={nodes.Plane424.geometry} material={materials.Base} />
                <mesh name="Plane424_1" castShadow receiveShadow geometry={nodes.Plane424_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight096" position={[-16.913, 0.38, 58.103]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane425" castShadow receiveShadow geometry={nodes.Plane425.geometry} material={materials.Base} />
                <mesh name="Plane425_1" castShadow receiveShadow geometry={nodes.Plane425_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>
            <group name="Stretlight097" position={[-25.428, 0.38, 58.103]} rotation={[Math.PI, 0, Math.PI]} scale={1.331}>
                <mesh name="Plane426" castShadow receiveShadow geometry={nodes.Plane426.geometry} material={materials.Base} />
                <mesh name="Plane426_1" castShadow receiveShadow geometry={nodes.Plane426_1.geometry} material={isNight ? materials.Lamp : materials.Base} />
            </group>

        </group>
    )
}

useGLTF.preload('/models/streetlights/Streetlights.glb')
