/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/floors/RoadAndFloors.glb -o src/components/models/floors/RoadAndFloors.tsx -k -s -r public/ 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { materials } from '@/consts/materials'

type GLTFResult = GLTF & {
  nodes: {
    Floor004: THREE.Mesh
    Floor007: THREE.Mesh
    Floor006: THREE.Mesh
    Floor005: THREE.Mesh
    Floor003: THREE.Mesh
    Floor002: THREE.Mesh
    Floor009: THREE.Mesh
    Floor016: THREE.Mesh
    Floor011: THREE.Mesh
    Road: THREE.Mesh
    Floor008: THREE.Mesh
    Floor001: THREE.Mesh
    Floor010: THREE.Mesh
    Floor: THREE.Mesh
    Floor012: THREE.Mesh
    Road001: THREE.Mesh
    Plane112: THREE.Mesh
    Plane112_1: THREE.Mesh
    Plane113: THREE.Mesh
    Plane113_1: THREE.Mesh
    Plane114: THREE.Mesh
    Plane114_1: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    Road: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function RoadAndFloors(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/floors/RoadAndFloors.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Floor004" castShadow receiveShadow geometry={nodes.Floor004.geometry} material={materials.Floor} position={[-15.962, 0, -19.689]} scale={[1, 1, 0.86]} />
      <mesh name="Floor007" castShadow receiveShadow geometry={nodes.Floor007.geometry} material={materials.Floor} position={[-16.015, 0.265, 4.162]} />
      <mesh name="Floor006" castShadow receiveShadow geometry={nodes.Floor006.geometry} material={materials.Floor} />
      <mesh name="Floor005" castShadow receiveShadow geometry={nodes.Floor005.geometry} material={materials.Floor} position={[15.502, 0, -0.258]} />
      <mesh name="Floor003" castShadow receiveShadow geometry={nodes.Floor003.geometry} material={materials.Floor} position={[0, 0, -15.966]} />
      <mesh name="Floor002" castShadow receiveShadow geometry={nodes.Floor002.geometry} material={materials.Floor} position={[15.502, 0, -50.588]} />
      <mesh name="Floor009" castShadow receiveShadow geometry={nodes.Floor009.geometry} material={materials.Floor} position={[15.502, 0, 31.471]} />
      <mesh name="Floor016" castShadow receiveShadow geometry={nodes.Floor016.geometry} material={materials.Floor} position={[15.502, 0, 15.661]} />
      <mesh name="Floor011" castShadow receiveShadow geometry={nodes.Floor011.geometry} material={materials.Floor} position={[-6.82, 0, 47.63]} />
      <mesh name="Road" castShadow receiveShadow geometry={nodes.Road.geometry} material={materials.Road} />
      <mesh name="Floor008" castShadow receiveShadow geometry={nodes.Floor008.geometry} material={materials.Floor} position={[15.381, 0, -34.414]} />
      <mesh name="Floor001" castShadow receiveShadow geometry={nodes.Floor001.geometry} material={materials.Floor} position={[-31.993, 0.568, -58.068]} />
      <mesh name="Floor010" castShadow receiveShadow geometry={nodes.Floor010.geometry} material={materials.Floor} position={[-0.394, 0, 31.471]} />
      <mesh name="Floor" castShadow receiveShadow geometry={nodes.Floor.geometry} material={materials.Floor} position={[15.502, 0, 47.63]} />
      <mesh name="Floor012" castShadow receiveShadow geometry={nodes.Floor012.geometry} material={materials.Floor} position={[4.548, -0.115, -63.541]} />
      <mesh name="Road001" castShadow receiveShadow geometry={nodes.Road001.geometry} material={materials.Floor} position={[0, -4.519, -0.108]} rotation={[0, 0, -Math.PI]} scale={[-25.869, -11.423, -56.849]} />
      <group name="Floor013" position={[48.112, 0, 67.887]}>
        <mesh name="Plane112" castShadow receiveShadow geometry={nodes.Plane112.geometry} material={materials.Floor} />
        <mesh name="Plane112_1" castShadow receiveShadow geometry={nodes.Plane112_1.geometry} material={materials.Grass} />
      </group>
      <group name="Floor014" position={[70.946, 0, 67.887]}>
        <mesh name="Plane113" castShadow receiveShadow geometry={nodes.Plane113.geometry} material={materials.Floor} />
        <mesh name="Plane113_1" castShadow receiveShadow geometry={nodes.Plane113_1.geometry} material={materials.Grass} />
      </group>
      <group name="Floor015" position={[48.112, 0, 47.759]}>
        <mesh name="Plane114" castShadow receiveShadow geometry={nodes.Plane114.geometry} material={materials.Floor} />
        <mesh name="Plane114_1" castShadow receiveShadow geometry={nodes.Plane114_1.geometry} material={materials.Grass} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/floors/RoadAndFloors.glb')
