// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/BlueSky.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useUserContext } from '@/context/UserContext';
import { materials } from '@/consts/materials';


export function BlueSky(props) {
  const { nodes } = useGLTF('./models/BlueSkyMap.glb');
  const { isNight } = useUserContext()

  const glass = isNight ? materials.GlassNight : materials.Glass

  return (
    <group {...props} >
      <mesh name="AC" castShadow receiveShadow geometry={nodes.AC.geometry} material={materials.Base} position={[3.358, 1.591, -23.402]} rotation={[0, 1.571, 0]} />
      <mesh name="AC001" castShadow receiveShadow geometry={nodes.AC001.geometry} material={materials.Base} position={[3.155, 3.344, 31.718]} rotation={[0, 1.571, 0]} />
      <mesh name="AC002" castShadow receiveShadow geometry={nodes.AC002.geometry} material={materials.Base} position={[3.837, 3.344, 31.718]} rotation={[0, 1.571, 0]} />
      <mesh name="AC003" castShadow receiveShadow geometry={nodes.AC003.geometry} material={materials.Base} position={[3.155, 3.344, 30.907]} rotation={[0, 1.571, 0]} />
      <mesh name="AC004" castShadow receiveShadow geometry={nodes.AC004.geometry} material={materials.Base} position={[3.837, 3.344, 30.907]} rotation={[0, 1.571, 0]} />


      <group name="airplane001" position={[-42.313, 0.747, -44.42]} rotation={[-Math.PI, 1.197, -Math.PI]}>
        <mesh name="Cube004" castShadow geometry={nodes.Cube004.geometry} material={materials.Base} />
        <mesh name="Cube004_1" castShadow geometry={nodes.Cube004_1.geometry} material={materials.Glass} />
      </group>

      <group name="airplane002" position={[-44.613, 0.747, -48.763]} rotation={[-Math.PI, 1.197, -Math.PI]}>
        <mesh name="Cube005" castShadow geometry={nodes.Cube005.geometry} material={materials.Base} />
        <mesh name="Cube005_1" castShadow geometry={nodes.Cube005_1.geometry} material={materials.Primary} />
      </group>
      <group name="Airport" position={[-29.809, 0.568, -63.787]} scale={2.274}>
        <mesh name="Plane016_1" castShadow geometry={nodes.Plane016_1.geometry} material={materials.Primary} />
        <mesh name="Plane016_2" castShadow geometry={nodes.Plane016_2.geometry} material={materials.Base} />
      </group>

      <group name="ambulance" position={[-14.138, 0.581, -22.555]} rotation={[0, Math.PI / 2, 0]} scale={1.623}>
        <mesh name="Cube019" castShadow geometry={nodes.Cube019.geometry} material={materials.Primary} />
        <mesh name="Cube019_1" castShadow geometry={nodes.Cube019_1.geometry} material={materials.Base} />
      </group>

      <group name="ambulance001" position={[-8.33, 0.416, -26.751]} scale={1.379}>
        <mesh name="Cube019" castShadow geometry={nodes.Cube019.geometry} material={materials.Primary} />
        <mesh name="Cube019_1" castShadow geometry={nodes.Cube019_1.geometry} material={materials.Base} />
      </group>
      <group name="ambulance002" position={[-14.138, 0.581, -23.911]} rotation={[0, Math.PI / 2, 0]} scale={1.623}>
        <mesh name="Cube007" castShadow geometry={nodes.Cube007.geometry} material={materials.Primary} />
        <mesh name="Cube007_1" castShadow geometry={nodes.Cube007_1.geometry} material={materials.Base} />
      </group>

      <mesh name="boat002" castShadow geometry={nodes.boat002.geometry} material={materials.Base} position={[-28.459, -0.859, 71.485]} />
      <mesh name="boat003" castShadow geometry={nodes.boat003.geometry} material={materials.Base} position={[-26.255, -0.859, 70.002]} rotation={[0, Math.PI / 3, 0]} />
      <group name="Bus" position={[8.061, 0.393, 1.603]} scale={0.472}>
        <mesh name="Plane143" castShadow geometry={nodes.Plane143.geometry} material={materials.Primary} />
        <mesh name="Plane143_1" castShadow geometry={nodes.Plane143_1.geometry} material={materials.Base} />
      </group>
      <group name="Bus001" position={[12.117, 0.323, 39.264]} rotation={[0, -Math.PI / 2, 0]} scale={0.635}>
        <mesh name="Plane143" castShadow geometry={nodes.Plane143.geometry} material={materials.Primary} />
        <mesh name="Plane143_1" castShadow geometry={nodes.Plane143_1.geometry} material={materials.Base} />
      </group>
      <group name="Bus002" position={[-14.45, 0.393, 54.018]} rotation={[0, -Math.PI / 2, 0]} scale={0.626}>
        <mesh name="Plane143" castShadow geometry={nodes.Plane143.geometry} material={materials.Primary} />
        <mesh name="Plane143_1" castShadow geometry={nodes.Plane143_1.geometry} material={materials.Base} />
      </group>
      <group name="Bus003" position={[-11.418, 0.393, -44.4]} rotation={[0, Math.PI / 2, 0]} scale={0.529}>
        <mesh name="Plane143" castShadow geometry={nodes.Plane143.geometry} material={materials.Primary} />
        <mesh name="Plane143_1" castShadow geometry={nodes.Plane143_1.geometry} material={materials.Base} />
      </group>




      <group name="Factory" position={[-12.219, 0.568, -50.272]} scale={[1.173, 1.005, 0.912]}>
        <mesh name="Plane208" castShadow geometry={nodes.Plane208.geometry} material={materials.Base} />
        <mesh name="Plane208_1" castShadow geometry={nodes.Plane208_1.geometry} material={materials.Primary} />
      </group>

      <mesh name="Factory001" castShadow geometry={nodes.Factory001.geometry} material={materials.Base} position={[-18.299, 0.65, -55.062]} scale={0.696} />
      <mesh name="Factory002" castShadow geometry={nodes.Factory002.geometry} material={materials.Base} position={[-4.962, 0.763, -54.797]} rotation={[0, Math.PI / 2, 0]} scale={0.735} />
      <mesh name="Factory003" castShadow geometry={nodes.Factory003.geometry} material={materials.Base} position={[-14.913, 0.65, -55.062]} scale={0.696} />
      <mesh name="Factory004" castShadow geometry={nodes.Factory004.geometry} material={materials.Base} position={[-11.625, 0.65, -55.062]} scale={0.696} />
      <group name="Fence002" position={[2.241, 0.571, 46.436]} rotation={[0, -Math.PI / 2, 0]} scale={0.829}>
        <mesh name="Plane142" castShadow geometry={nodes.Plane142.geometry} material={materials.Base} />
        <mesh name="Plane142_1" castShadow geometry={nodes.Plane142_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift" position={[13.944, 0.877, -47.523]} scale={0.845}>
        <mesh name="Plane146" castShadow geometry={nodes.Plane146.geometry} material={materials.Base} />
        <mesh name="Plane146_1" castShadow geometry={nodes.Plane146_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift001" position={[8.68, 0.877, -47.372]} rotation={[0, 0.558, 0]} scale={0.845}>
        <mesh name="Plane146" castShadow geometry={nodes.Plane146.geometry} material={materials.Base} />
        <mesh name="Plane146_1" castShadow geometry={nodes.Plane146_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift002" position={[2.164, 0.877, -47.402]} rotation={[0, 1.321, 0]} scale={0.845}>
        <mesh name="Plane147" castShadow geometry={nodes.Plane147.geometry} material={materials.Base} />
        <mesh name="Plane147_1" castShadow geometry={nodes.Plane147_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift003" position={[7.099, 0.877, -48.311]} rotation={[0, -0.009, 0]} scale={0.845}>
        <mesh name="Plane175" castShadow geometry={nodes.Plane175.geometry} material={materials.Base} />
        <mesh name="Plane175_1" castShadow geometry={nodes.Plane175_1.geometry} material={materials.Primary} />
      </group>
      <group name="Gas_Station001" position={[15.194, 0.675, 17.418]} scale={0.561}>
        <mesh name="Plane318" castShadow geometry={nodes.Plane318.geometry} material={materials.Glass} />
        <mesh name="Plane318_1" castShadow geometry={nodes.Plane318_1.geometry} material={materials.Base} />
        <mesh name="Plane318_2" castShadow geometry={nodes.Plane318_2.geometry} material={materials.Primary} />
      </group>
      <mesh name="Halte" castShadow geometry={nodes.Halte.geometry} material={materials.Base} position={[-5.884, 0.568, -16.257]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte001" castShadow geometry={nodes.Halte001.geometry} material={materials.Base} position={[-6.132, 0.568, 14.64]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte002" castShadow geometry={nodes.Halte002.geometry} material={materials.Base} position={[9.421, 0.568, 0.031]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte003" castShadow geometry={nodes.Halte003.geometry} material={materials.Base} position={[9.63, 0.568, -31.252]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte004" castShadow geometry={nodes.Halte004.geometry} material={materials.Base} position={[-5.228, 0.568, -46.221]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte005" castShadow geometry={nodes.Halte005.geometry} material={materials.Base} position={[15.056, 0.568, 40.574]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.717, 0.303, 0.303]} />

      <group name="Hangar" position={[-43.478, 0.420, -60.989]} rotation={[Math.PI, 0, Math.PI]} scale={1.299}>
        <mesh name="Plane007" castShadow geometry={nodes.Plane007.geometry} material={materials.Base} />
        <mesh name="Plane007_1" castShadow geometry={nodes.Plane007_1.geometry} material={materials.Primary} />
      </group>
      <group name="Hangar001" position={[-43.478, 0.420, -55.012]} rotation={[Math.PI, 0, Math.PI]} scale={1.299}>
        <mesh name="Plane252" castShadow geometry={nodes.Plane252.geometry} material={materials.Base} />
        <mesh name="Plane252_1" castShadow geometry={nodes.Plane252_1.geometry} material={materials.Primary} />
      </group>
      <group name="Hangar002" position={[-43.478, 0.420, -66.839]} rotation={[Math.PI, 0, Math.PI]} scale={1.299}>
        <mesh name="Plane253" castShadow geometry={nodes.Plane253.geometry} material={materials.Base} />
        <mesh name="Plane253_1" castShadow geometry={nodes.Plane253_1.geometry} material={materials.Primary} />
      </group>

      <group name="harbour" position={[14.945, 1.486, -69.53]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007002" castShadow geometry={nodes.mesh980636007002.geometry} material={materials.Base} />
        <mesh name="mesh980636007002_1" castShadow geometry={nodes.mesh980636007002_1.geometry} material={materials.Primary} />
      </group>
      <group name="harbour001" position={[-2.491, 1.486, -69.53]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007008" castShadow geometry={nodes.mesh980636007008.geometry} material={materials.Base} />
        <mesh name="mesh980636007008_1" castShadow geometry={nodes.mesh980636007008_1.geometry} material={materials.Primary} />
      </group>
      <group name="Helicopter" position={[-37.108, 0.402, -40.562]} rotation={[0, 0.704, 0]} scale={0.11}>
        <mesh name="Cube-Mesh" castShadow geometry={nodes['Cube-Mesh'].geometry} material={materials.Base} />
        <mesh name="Cube-Mesh_1" castShadow geometry={nodes['Cube-Mesh_1'].geometry} material={materials.Glass} />
        <mesh name="Cube-Mesh_2" castShadow geometry={nodes['Cube-Mesh_2'].geometry} material={materials.Primary} />
      </group>
      <group name="hospital001" position={[-17.243, 2.429, -20.778]} rotation={[0, Math.PI / 2, 0]} scale={[1.443, 1.443, 1.688]}>
        <mesh name="Cube002" castShadow geometry={nodes.Cube002.geometry} material={materials.Base} />
        <mesh name="Cube002_1" castShadow geometry={nodes.Cube002_1.geometry} material={materials.Primary} />
      </group>
      <group name="Hotel" position={[-18.292, 0.474, 14.677]} rotation={[0, Math.PI / 2, 0]} scale={0.594}>
        <mesh name="Plane246" castShadow geometry={nodes.Plane246.geometry} material={materials.Base} />
        <mesh name="Plane246_1" castShadow geometry={nodes.Plane246_1.geometry} material={materials.Primary} />
      </group>
      <group name="House" position={[-18.803, 0.569, 49.818]} scale={0.663}>
        <mesh name="Plane011" castShadow geometry={nodes.Plane011.geometry} material={materials.Grass} />
        <mesh name="Plane011_1" castShadow geometry={nodes.Plane011_1.geometry} material={materials.Base} />
        <mesh name="Plane011_2" castShadow geometry={nodes.Plane011_2.geometry} material={materials.Glass} />
      </group>
      <group name="House001" position={[19.068, 0.569, 2.207]} rotation={[0, Math.PI / 2, 0]} scale={0.638}>
        <mesh name="Plane011" castShadow geometry={nodes.Plane011.geometry} material={materials.Grass} />
        <mesh name="Plane011_1" castShadow geometry={nodes.Plane011_1.geometry} material={materials.Base} />
        <mesh name="Plane011_2" castShadow geometry={nodes.Plane011_2.geometry} material={materials.Glass} />
      </group>
      <group name="House002" position={[-19.836, 0.569, -29.851]} rotation={[Math.PI, -1.536, Math.PI]} scale={0.642}>
        <mesh name="Plane011" castShadow geometry={nodes.Plane011.geometry} material={materials.Grass} />
        <mesh name="Plane011_1" castShadow geometry={nodes.Plane011_1.geometry} material={materials.Base} />
        <mesh name="Plane011_2" castShadow geometry={nodes.Plane011_2.geometry} material={materials.Glass} />
      </group>
      <group name="House003" position={[9.961, 0.569, 17.975]} scale={0.67}>
        <mesh name="Plane011" castShadow geometry={nodes.Plane011.geometry} material={materials.Grass} />
        <mesh name="Plane011_1" castShadow geometry={nodes.Plane011_1.geometry} material={materials.Base} />
        <mesh name="Plane011_2" castShadow geometry={nodes.Plane011_2.geometry} material={materials.Glass} />
      </group>
      <group name="House010" position={[-5.824, 0.569, 43.194]} rotation={[Math.PI, 0, Math.PI]} scale={0.721}>
        <mesh name="Plane011" castShadow geometry={nodes.Plane011.geometry} material={materials.Grass} />
        <mesh name="Plane011_1" castShadow geometry={nodes.Plane011_1.geometry} material={materials.Base} />
        <mesh name="Plane011_2" castShadow geometry={nodes.Plane011_2.geometry} material={materials.Glass} />
      </group>
      <group name="House014" position={[5.175, 0.569, 11.582]} rotation={[Math.PI, 0, Math.PI]} scale={0.668}>
        <mesh name="Plane011" castShadow geometry={nodes.Plane011.geometry} material={materials.Grass} />
        <mesh name="Plane011_1" castShadow geometry={nodes.Plane011_1.geometry} material={materials.Base} />
        <mesh name="Plane011_2" castShadow geometry={nodes.Plane011_2.geometry} material={materials.Glass} />
      </group>
      <group name="house1" position={[10.879, 0.937, 34.287]} scale={0.905}>
        <mesh name="Plane064" castShadow geometry={nodes.Plane064.geometry} material={materials.Base} />
        <mesh name="Plane064_1" castShadow geometry={nodes.Plane064_1.geometry} material={materials.Primary} />
      </group>
      <group name="house006" position={[12.436, 0.937, 26.495]} rotation={[Math.PI, 0, Math.PI]} scale={0.905}>
        <mesh name="Plane064" castShadow geometry={nodes.Plane064.geometry} material={materials.Base} />
        <mesh name="Plane064_1" castShadow geometry={nodes.Plane064_1.geometry} material={materials.Primary} />
      </group>
      <group name="house2" position={[15.1, 1.036, 34.217]} scale={0.905}>
        <mesh name="Plane065" castShadow geometry={nodes.Plane065.geometry} material={materials.Base} />
        <mesh name="Plane065_1" castShadow geometry={nodes.Plane065_1.geometry} material={materials.Primary} />
      </group>
      <group name="House004" position={[18.632, 0.568, -3.11]} rotation={[0, Math.PI / 2, 0]} scale={0.646}>
        <mesh name="Plane017" castShadow geometry={nodes.Plane017.geometry} material={materials.Base} />
        <mesh name="Plane017_1" castShadow geometry={nodes.Plane017_1.geometry} material={materials.Primary} />
        <mesh name="Plane017_2" castShadow geometry={nodes.Plane017_2.geometry} material={materials.Grass} />
      </group>
      <group name="House006" position={[12.898, 0.568, 1.924]} rotation={[0, -Math.PI / 2, 0]} scale={0.626}>
        <mesh name="Plane017" castShadow geometry={nodes.Plane017.geometry} material={materials.Base} />
        <mesh name="Plane017_1" castShadow geometry={nodes.Plane017_1.geometry} material={materials.Primary} />
        <mesh name="Plane017_2" castShadow geometry={nodes.Plane017_2.geometry} material={materials.Grass} />
      </group>
      <group name="House009" position={[-5.958, 0.568, 49.558]} scale={0.689}>
        <mesh name="Plane017" castShadow geometry={nodes.Plane017.geometry} material={materials.Base} />
        <mesh name="Plane017_1" castShadow geometry={nodes.Plane017_1.geometry} material={materials.Primary} />
        <mesh name="Plane017_2" castShadow geometry={nodes.Plane017_2.geometry} material={materials.Grass} />
      </group>
      <group name="House011" position={[-12.286, 0.568, 43.679]} rotation={[Math.PI, 0, Math.PI]} scale={0.727}>
        <mesh name="Plane017" castShadow geometry={nodes.Plane017.geometry} material={materials.Base} />
        <mesh name="Plane017_1" castShadow geometry={nodes.Plane017_1.geometry} material={materials.Primary} />
        <mesh name="Plane017_2" castShadow geometry={nodes.Plane017_2.geometry} material={materials.Grass} />
      </group>
      <group name="House013" position={[0.386, 0.568, 11.511]} rotation={[Math.PI, 0, Math.PI]} scale={0.671}>
        <mesh name="Plane017" castShadow geometry={nodes.Plane017.geometry} material={materials.Base} />
        <mesh name="Plane017_1" castShadow geometry={nodes.Plane017_1.geometry} material={materials.Primary} />
        <mesh name="Plane017_2" castShadow geometry={nodes.Plane017_2.geometry} material={materials.Grass} />
      </group>
      <group name="House018" position={[-19.284, 0.568, -38.965]} rotation={[0, -Math.PI / 2, 0]} scale={0.68}>
        <mesh name="Plane017" castShadow geometry={nodes.Plane017.geometry} material={materials.Base} />
        <mesh name="Plane017_1" castShadow geometry={nodes.Plane017_1.geometry} material={materials.Primary} />
        <mesh name="Plane017_2" castShadow geometry={nodes.Plane017_2.geometry} material={materials.Grass} />
      </group>
      <group name="House005" position={[12.876, 0.568, -7.8]} rotation={[0, -Math.PI / 2, 0]} scale={[0.741, 0.741, 0.728]}>
        <mesh name="Plane145" castShadow geometry={nodes.Plane145.geometry} material={materials.Base} />
        <mesh name="Plane145_1" castShadow geometry={nodes.Plane145_1.geometry} material={materials.Primary} />
        <mesh name="Plane145_2" castShadow geometry={nodes.Plane145_2.geometry} material={materials.Grass} />
      </group>
      <group name="House008" position={[-12.356, 0.568, 49.396]} scale={0.74}>
        <mesh name="Plane145" castShadow geometry={nodes.Plane145.geometry} material={materials.Base} />
        <mesh name="Plane145_1" castShadow geometry={nodes.Plane145_1.geometry} material={materials.Primary} />
        <mesh name="Plane145_2" castShadow geometry={nodes.Plane145_2.geometry} material={materials.Grass} />
      </group>
      <group name="House012" position={[-18.316, 0.568, 43.949]} rotation={[Math.PI, 0, Math.PI]} scale={0.765}>
        <mesh name="Plane145" castShadow geometry={nodes.Plane145.geometry} material={materials.Base} />
        <mesh name="Plane145_1" castShadow geometry={nodes.Plane145_1.geometry} material={materials.Primary} />
        <mesh name="Plane145_2" castShadow geometry={nodes.Plane145_2.geometry} material={materials.Grass} />
      </group>
      <group name="House015" position={[15.421, 0.568, 11.658]} rotation={[Math.PI, 0, Math.PI]} scale={0.685}>
        <mesh name="Plane145" castShadow geometry={nodes.Plane145.geometry} material={materials.Base} />
        <mesh name="Plane145_1" castShadow geometry={nodes.Plane145_1.geometry} material={materials.Primary} />
        <mesh name="Plane145_2" castShadow geometry={nodes.Plane145_2.geometry} material={materials.Grass} />
      </group>
      <group name="House017" position={[-18.947, 0.568, -34.134]} rotation={[0, -Math.PI / 2, 0]} scale={0.696}>
        <mesh name="Plane145" castShadow geometry={nodes.Plane145.geometry} material={materials.Base} />
        <mesh name="Plane145_1" castShadow geometry={nodes.Plane145_1.geometry} material={materials.Primary} />
        <mesh name="Plane145_2" castShadow geometry={nodes.Plane145_2.geometry} material={materials.Grass} />
      </group>
      <group name="house005" position={[16.272, 1.036, 26.755]} rotation={[Math.PI, 0, Math.PI]} scale={0.905}>
        <mesh name="Plane067" castShadow geometry={nodes.Plane067.geometry} material={materials.Base} />
        <mesh name="Plane067_1" castShadow geometry={nodes.Plane067_1.geometry} material={materials.Primary} />
      </group>
      <group name="House007" position={[12.599, 0.569, -2.742]} rotation={[0, -Math.PI / 2, 0]} scale={0.638}>
        <mesh name="Plane178" castShadow geometry={nodes.Plane178.geometry} material={materials.Grass} />
        <mesh name="Plane178_1" castShadow geometry={nodes.Plane178_1.geometry} material={materials.Base} />
        <mesh name="Plane178_2" castShadow geometry={nodes.Plane178_2.geometry} material={materials.Glass} />
      </group>
      <group name="House016" position={[-3.017, 0.568, 17.401]} scale={0.685}>
        <mesh name="Plane193" castShadow geometry={nodes.Plane193.geometry} material={materials.Base} />
        <mesh name="Plane193_1" castShadow geometry={nodes.Plane193_1.geometry} material={materials.Primary} />
        <mesh name="Plane193_2" castShadow geometry={nodes.Plane193_2.geometry} material={materials.Grass} />
      </group>
      <group name="library" position={[15.549, 0.568, -35.713]} rotation={[0, -Math.PI / 2, 0]} scale={1.087}>
        <mesh name="Plane004_1" castShadow geometry={nodes.Plane004_1.geometry} material={materials.Glass} />
        <mesh name="Plane004_2" castShadow geometry={nodes.Plane004_2.geometry} material={materials.Base} />
      </group>

      <group name="NDIS" position={[15.53, 0.568, -18.281]} rotation={[0, -Math.PI / 2, 0]} scale={1.18}>
        <mesh name="Plane005" castShadow geometry={nodes.Plane005.geometry} material={materials.Glass} />
        <mesh name="Plane005_1" castShadow geometry={nodes.Plane005_1.geometry} material={materials.Base} />
        <mesh name="Plane005_2" castShadow geometry={nodes.Plane005_2.geometry} material={materials.Grass} />
      </group>

      <group name="Office001" position={[-18.283, 0.474, -9.466]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.711}>
        <mesh name="Plane247" castShadow geometry={nodes.Plane247.geometry} material={materials.Primary} />
        <mesh name="Plane247_1" castShadow geometry={nodes.Plane247_1.geometry} material={materials.Base} />
      </group>



      <mesh name="Plane020" castShadow geometry={nodes.Plane020.geometry} material={materials.Grass} position={[0, 0.031, -15.966]} />
      <mesh name="Plane023" castShadow geometry={nodes.Plane023.geometry} material={materials.Grass} position={[-6.82, 0, 47.63]} />
      <mesh name="Plane024" castShadow geometry={nodes.Plane024.geometry} material={materials.Grass} position={[-12.099, 0.471, -49.968]} />
      <mesh name="Plane025" castShadow geometry={nodes.Plane025.geometry} material={materials.Water} position={[0, 0.031, -15.966]} />
      <mesh name="Plane026" castShadow geometry={nodes.Plane026.geometry} material={materials.Grass} position={[15.502, 0, -0.258]} />
      <mesh name="Plane027" castShadow geometry={nodes.Plane027.geometry} material={materials.Base} position={[15.502, 0, -0.258]} />
      <mesh name="Plane028" castShadow geometry={nodes.Plane028.geometry} material={materials.Water} position={[15.502, 0, -0.258]} />
      <mesh name="Plane029" castShadow geometry={nodes.Plane029.geometry} material={materials.Grass} position={[15.502, 0, -0.258]} />
      <mesh name="Plane014" castShadow geometry={nodes.Plane014.geometry} material={materials.Grass} position={[-14.286, 0.06, -32.846]} scale={[6.788, 8.798, 12.985]} />
      <mesh name="Plane015" castShadow geometry={nodes.Plane015.geometry} material={materials.Grass} position={[18.664, 0, 15.862]} scale={[1.391, 1, 1.159]} />
      <mesh name="Plane016" castShadow geometry={nodes.Plane016.geometry} material={materials.Grass} position={[-16.015, 0.265, 3.64]} />


      <group name="Stadion" position={[-0.039, 0.61, -33.922]} scale={[0.568, 0.25, 0.287]}>
        <mesh name="Plane012" castShadow geometry={nodes.Plane012.geometry} material={materials.Glass} />
        <mesh name="Plane012_1" castShadow geometry={nodes.Plane012_1.geometry} material={materials.Base} />
      </group>
      <mesh name="Stadion001" castShadow geometry={nodes.Stadion001.geometry} material={materials.Grass} position={[-0.039, 0.608, -33.922]} scale={[0.568, 0.25, 0.287]} />
      <mesh name="Stadion002" castShadow geometry={nodes.Stadion002.geometry} material={materials.Grass} position={[-0.039, 0.61, -33.922]} scale={[0.568, 0.25, 0.287]} />



      <group name="Truck" position={[7.257, 0.533, -10.516]} rotation={[Math.PI, 0, Math.PI]} scale={1.135}>
        <mesh name="mesh980636007005" castShadow geometry={nodes.mesh980636007005.geometry} material={materials.Base} />
        <mesh name="mesh980636007005_1" castShadow geometry={nodes.mesh980636007005_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck002" position={[10.505, 0.709, -65.147]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007005" castShadow geometry={nodes.mesh980636007005.geometry} material={materials.Base} />
        <mesh name="mesh980636007005_1" castShadow geometry={nodes.mesh980636007005_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck001" position={[22.807, 0.496, -58.081]} rotation={[0, 1.521, 0]} scale={1.188}>
        <mesh name="mesh980636007003" castShadow geometry={nodes.mesh980636007003.geometry} material={materials.Base} />
        <mesh name="mesh980636007003_1" castShadow geometry={nodes.mesh980636007003_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck004" position={[16.572, 0.692, -68.668]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007003" castShadow geometry={nodes.mesh980636007003.geometry} material={materials.Base} />
        <mesh name="mesh980636007003_1" castShadow geometry={nodes.mesh980636007003_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck003" position={[7.634, 0.709, -68.614]} rotation={[0, 1.571, 0]}>
        <mesh name="mesh980636007007" castShadow geometry={nodes.mesh980636007007.geometry} material={materials.Base} />
        <mesh name="mesh980636007007_1" castShadow geometry={nodes.mesh980636007007_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck005" position={[9.251, 0.533, 21.793]} rotation={[0, 1.571, 0]} scale={1.064}>
        <mesh name="mesh980636007001" castShadow geometry={nodes.mesh980636007001.geometry} material={materials.Base} />
        <mesh name="mesh980636007001_1" castShadow geometry={nodes.mesh980636007001_1.geometry} material={materials.Primary} />
      </group>
      <group name="Vessel" position={[14.103, 1.375, -69.039]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007004" castShadow geometry={nodes.mesh980636007004.geometry} material={materials.Base} />
        <mesh name="mesh980636007004_1" castShadow geometry={nodes.mesh980636007004_1.geometry} material={materials.Primary} />
      </group>
      <group name="Vessel001" position={[1.786, 1.375, -87.523]} rotation={[0, 0.973, 0]}>
        <mesh name="mesh980636007006" castShadow geometry={nodes.mesh980636007006.geometry} material={materials.Base} />
        <mesh name="mesh980636007006_1" castShadow geometry={nodes.mesh980636007006_1.geometry} material={materials.Primary} />
      </group>
      <group name="Vessel002" position={[-11.814, 1.375, -72.591]} rotation={[-Math.PI, 0.294, -Math.PI]}>
        <mesh name="mesh980636007010" castShadow geometry={nodes.mesh980636007010.geometry} material={materials.Base} />
        <mesh name="mesh980636007010_1" castShadow geometry={nodes.mesh980636007010_1.geometry} material={materials.Primary} />
      </group>
      <group name="warehouse1" position={[9.561, 2.068, -52.808]} scale={[0.945, 0.829, 0.69]}>
        <mesh name="Plane020_1" castShadow geometry={nodes.Plane020_1.geometry} material={materials.Base} />
        <mesh name="Plane020_2" castShadow geometry={nodes.Plane020_2.geometry} material={materials.Primary} />
      </group>
      <group name="warehouse2" position={[15.486, 2.092, -52.572]} scale={[1, 1, 0.819]}>
        <mesh name="Plane040" castShadow geometry={nodes.Plane040.geometry} material={materials.Base} />
        <mesh name="Plane040_1" castShadow geometry={nodes.Plane040_1.geometry} material={materials.Glass} />
      </group>
      <group name="warehouse003" position={[2.237, 2.068, -52.808]} scale={[0.945, 0.829, 0.69]}>
        <mesh name="Plane159" castShadow geometry={nodes.Plane159.geometry} material={materials.Base} />
        <mesh name="Plane159_1" castShadow geometry={nodes.Plane159_1.geometry} material={materials.Primary} />
      </group>
      <group name="Water_Statue" position={[-0.013, 1.31, -13.751]} scale={1.225}>
        <mesh name="Plane015_1" castShadow geometry={nodes.Plane015_1.geometry} material={materials.Base} />
        <mesh name="Plane015_2" castShadow geometry={nodes.Plane015_2.geometry} material={materials.Water} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/BlueSkyMap.glb')
