//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/BlueSkyStatue.glb -s -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function BlueSkyStatue(props) {
  const { nodes, materials } = useGLTF('./models/BlueSkyStatue.glb')

  const logoRef = useRef(null)
  useFrame((state, delta) => {
    if (logoRef.current) {
      logoRef.current.rotation.y += delta * 1.5; // Adjust rotation speed by changing the multiplier, here it's set to 2
    }
  });

  return (
    <group {...props} dispose={null}>
      <group name="statue" position={[-0.324, 0.525, -1.093]} rotation={[0, Math.PI / 2, 0]} scale={1}>
        <mesh ref={logoRef} name="Circle001" castShadow receiveShadow geometry={nodes.Circle001.geometry} material={materials.Material} />
        <mesh name="Circle001_1" castShadow receiveShadow geometry={nodes.Circle001_1.geometry} material={materials.Base} />
        <mesh name="Circle001_2" receiveShadow geometry={nodes.Circle001_2.geometry} material={materials.Water} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/BlueSkyStatue.glb')
