// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/BlueSky.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useUserContext } from '@/context/UserContext';
import { materials } from '@/consts/materials';


export function BlueSky(props) {
  const { nodes } = useGLTF('./models/BlueSkyMap.glb');
  const { isNight, quality } = useUserContext()

  const glass = isNight ? materials.GlassNight : materials.Glass
  const castShadow = quality >= 1 ? true : false

  return (
    <group {...props} >
      <mesh name="AC" castShadow={castShadow} geometry={nodes.AC.geometry} material={materials.Base} position={[3.358, 1.591, -23.402]} rotation={[0, 1.571, 0]} />
      <mesh name="AC001" castShadow={castShadow} geometry={nodes.AC001.geometry} material={materials.Base} position={[3.155, 3.344, 31.718]} rotation={[0, 1.571, 0]} />
      <mesh name="AC002" castShadow={castShadow} geometry={nodes.AC002.geometry} material={materials.Base} position={[3.837, 3.344, 31.718]} rotation={[0, 1.571, 0]} />
      <mesh name="AC003" castShadow={castShadow} geometry={nodes.AC003.geometry} material={materials.Base} position={[3.155, 3.344, 30.907]} rotation={[0, 1.571, 0]} />
      <mesh name="AC004" castShadow={castShadow} geometry={nodes.AC004.geometry} material={materials.Base} position={[3.837, 3.344, 30.907]} rotation={[0, 1.571, 0]} />


      <group name="airplane001" position={[-42.313, 0.747, -44.42]} rotation={[-Math.PI, 1.197, -Math.PI]}>
        <mesh name="Cube004" castShadow={castShadow} geometry={nodes.Cube004.geometry} material={materials.Base} />
        <mesh name="Cube004_1" castShadow={castShadow} geometry={nodes.Cube004_1.geometry} material={materials.Glass} />
      </group>

      <group name="airplane002" position={[-44.613, 0.747, -48.763]} rotation={[-Math.PI, 1.197, -Math.PI]}>
        <mesh name="Cube005" castShadow={castShadow} geometry={nodes.Cube005.geometry} material={materials.Base} />
        <mesh name="Cube005_1" castShadow={castShadow} geometry={nodes.Cube005_1.geometry} material={materials.Primary} />
      </group>



      <group name="ambulance001" position={[-7, 0.416, -25]} scale={1.379}>
        <mesh name="Cube019" castShadow={castShadow} geometry={nodes.Cube019.geometry} material={materials.Primary} />
        <mesh name="Cube019_1" castShadow={castShadow} geometry={nodes.Cube019_1.geometry} material={materials.Base} />
      </group>


      <mesh name="boat002" castShadow={castShadow} geometry={nodes.boat002.geometry} material={materials.Base} position={[-28.459, -0.859, 71.485]} />
      <mesh name="boat003" castShadow={castShadow} geometry={nodes.boat003.geometry} material={materials.Base} position={[-26.255, -0.859, 70.002]} rotation={[0, Math.PI / 3, 0]} />
      <group name="Bus" position={[8.061, 0.393, 1.603]} scale={0.472}>
        <mesh name="Plane143" castShadow={castShadow} geometry={nodes.Plane143.geometry} material={materials.Primary} />
        <mesh name="Plane143_1" castShadow={castShadow} geometry={nodes.Plane143_1.geometry} material={materials.Base} />
      </group>
      <group name="Bus001" position={[12.117, 0.323, 39.264]} rotation={[0, -Math.PI / 2, 0]} scale={0.635}>
        <mesh name="Plane143" castShadow={castShadow} geometry={nodes.Plane143.geometry} material={materials.Primary} />
        <mesh name="Plane143_1" castShadow={castShadow} geometry={nodes.Plane143_1.geometry} material={materials.Base} />
      </group>

      <group name="Bus003" position={[-12, 0.393, -42.75]} rotation={[0, Math.PI / 2, 0]} scale={0.529}>
        <mesh name="Plane143" castShadow={castShadow} geometry={nodes.Plane143.geometry} material={materials.Primary} />
        <mesh name="Plane143_1" castShadow={castShadow} geometry={nodes.Plane143_1.geometry} material={materials.Base} />
      </group>




      <group name="Fence002" position={[2.241, 0.571, 46.436]} rotation={[0, -Math.PI / 2, 0]} scale={0.829}>
        <mesh name="Plane142" castShadow={castShadow} geometry={nodes.Plane142.geometry} material={materials.Base} />
        <mesh name="Plane142_1" castShadow={castShadow} geometry={nodes.Plane142_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift" position={[13.944, 0.877, -47.523]} scale={0.845}>
        <mesh name="Plane146" castShadow={castShadow} geometry={nodes.Plane146.geometry} material={materials.Base} />
        <mesh name="Plane146_1" castShadow={castShadow} geometry={nodes.Plane146_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift001" position={[8.68, 0.877, -47.372]} rotation={[0, 0.558, 0]} scale={0.845}>
        <mesh name="Plane146" castShadow={castShadow} geometry={nodes.Plane146.geometry} material={materials.Base} />
        <mesh name="Plane146_1" castShadow={castShadow} geometry={nodes.Plane146_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift002" position={[2.164, 0.877, -47.402]} rotation={[0, 1.321, 0]} scale={0.845}>
        <mesh name="Plane147" castShadow={castShadow} geometry={nodes.Plane147.geometry} material={materials.Base} />
        <mesh name="Plane147_1" castShadow={castShadow} geometry={nodes.Plane147_1.geometry} material={materials.Primary} />
      </group>
      <group name="forklift003" position={[7.099, 0.877, -48.311]} rotation={[0, -0.009, 0]} scale={0.845}>
        <mesh name="Plane175" castShadow={castShadow} geometry={nodes.Plane175.geometry} material={materials.Base} />
        <mesh name="Plane175_1" castShadow={castShadow} geometry={nodes.Plane175_1.geometry} material={materials.Primary} />
      </group>

      <mesh name="Halte" castShadow={castShadow} geometry={nodes.Halte.geometry} material={materials.Base} position={[-5.884, 0.568, -16.257]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte001" castShadow={castShadow} geometry={nodes.Halte001.geometry} material={materials.Base} position={[-6.132, 0.568, 14.64]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte002" castShadow={castShadow} geometry={nodes.Halte002.geometry} material={materials.Base} position={[9.421, 0.568, 0.031]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte003" castShadow={castShadow} geometry={nodes.Halte003.geometry} material={materials.Base} position={[9.63, 0.568, -31.252]} rotation={[0, -Math.PI / 2, 0]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte004" castShadow={castShadow} geometry={nodes.Halte004.geometry} material={materials.Base} position={[-5.228, 0.568, -46.221]} scale={[0.717, 0.303, 0.303]} />
      <mesh name="Halte005" castShadow={castShadow} geometry={nodes.Halte005.geometry} material={materials.Base} position={[15.056, 0.568, 40.574]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.717, 0.303, 0.303]} />

      <group name="Helicopter" position={[-37.108, 0.402, -40.562]} rotation={[0, 0.704, 0]} scale={0.11}>
        <mesh name="Cube-Mesh" castShadow={castShadow} geometry={nodes['Cube-Mesh'].geometry} material={materials.Base} />
        <mesh name="Cube-Mesh_1" castShadow={castShadow} geometry={nodes['Cube-Mesh_1'].geometry} material={materials.Glass} />
        <mesh name="Cube-Mesh_2" castShadow={castShadow} geometry={nodes['Cube-Mesh_2'].geometry} material={materials.Primary} />
      </group>


      <mesh name="Plane020" castShadow={castShadow} geometry={nodes.Plane020.geometry} material={materials.Grass} position={[0, 0.031, -15.966]} />
      <mesh name="Plane023" castShadow={castShadow} geometry={nodes.Plane023.geometry} material={materials.Grass} position={[-6.82, 0, 47.63]} />
      <mesh name="Plane024" castShadow={castShadow} geometry={nodes.Plane024.geometry} material={materials.Grass} position={[-12.099, 0.471, -49.968]} />
      <mesh name="Plane025" castShadow={castShadow} geometry={nodes.Plane025.geometry} material={materials.Water} position={[0, 0.031, -15.966]} />
      <mesh name="Plane026" castShadow={castShadow} geometry={nodes.Plane026.geometry} material={materials.Grass} position={[15.502, 0, -0.258]} />
      <mesh name="Plane027" castShadow={castShadow} geometry={nodes.Plane027.geometry} material={materials.Base} position={[15.502, 0, -0.258]} />
      <mesh name="Plane028" castShadow={castShadow} geometry={nodes.Plane028.geometry} material={materials.Water} position={[15.502, 0, -0.258]} />
      <mesh name="Plane029" castShadow={castShadow} geometry={nodes.Plane029.geometry} material={materials.Grass} position={[15.502, 0, -0.258]} />
      <mesh name="Plane014" castShadow={castShadow} geometry={nodes.Plane014.geometry} material={materials.Grass} position={[-14.286, 0.06, -32.846]} scale={[6.788, 8.798, 12.985]} />
      <mesh name="Plane015" castShadow={castShadow} geometry={nodes.Plane015.geometry} material={materials.Grass} position={[18.664, 0, 15.862]} scale={[1.391, 1, 1.159]} />
      <mesh name="Plane016" castShadow={castShadow} geometry={nodes.Plane016.geometry} material={materials.Grass} position={[-16.015, 0.265, 3.64]} />

      <group name="Truck" position={[7.257, 0.533, -10.516]} rotation={[Math.PI, 0, Math.PI]} scale={1.135}>
        <mesh name="mesh980636007005" castShadow={castShadow} geometry={nodes.mesh980636007005.geometry} material={materials.Base} />
        <mesh name="mesh980636007005_1" castShadow={castShadow} geometry={nodes.mesh980636007005_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck002" position={[10.505, 0.709, -65.147]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007005" castShadow={castShadow} geometry={nodes.mesh980636007005.geometry} material={materials.Base} />
        <mesh name="mesh980636007005_1" castShadow={castShadow} geometry={nodes.mesh980636007005_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck001" position={[16, 0.496, -61]} rotation={[0, Math.PI, 0]} scale={1.188}>
        <mesh name="mesh980636007003" castShadow={castShadow} geometry={nodes.mesh980636007003.geometry} material={materials.Base} />
        <mesh name="mesh980636007003_1" castShadow={castShadow} geometry={nodes.mesh980636007003_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck004" position={[7, 0.692, -61]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007003" castShadow={castShadow} geometry={nodes.mesh980636007003.geometry} material={materials.Base} />
        <mesh name="mesh980636007003_1" castShadow={castShadow} geometry={nodes.mesh980636007003_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck003" position={[3, 0.709, -61]} rotation={[0, 1.571, 0]}>
        <mesh name="mesh980636007007" castShadow={castShadow} geometry={nodes.mesh980636007007.geometry} material={materials.Base} />
        <mesh name="mesh980636007007_1" castShadow={castShadow} geometry={nodes.mesh980636007007_1.geometry} material={materials.Primary} />
      </group>
      <group name="Truck005" position={[8.4, 0.533, 28]} rotation={[0, Math.PI, 0]} scale={1.064}>
        <mesh name="mesh980636007001" castShadow={castShadow} geometry={nodes.mesh980636007001.geometry} material={materials.Base} />
        <mesh name="mesh980636007001_1" castShadow={castShadow} geometry={nodes.mesh980636007001_1.geometry} material={materials.Primary} />
      </group>
      <group name="Vessel" position={[14.103, 1.375, -69.039]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="mesh980636007004" castShadow={castShadow} geometry={nodes.mesh980636007004.geometry} material={materials.Base} />
        <mesh name="mesh980636007004_1" castShadow={castShadow} geometry={nodes.mesh980636007004_1.geometry} material={materials.Primary} />
      </group>
      <group name="Vessel001" position={[1.786, 1.375, -87.523]} rotation={[0, 0.973, 0]}>
        <mesh name="mesh980636007006" castShadow={castShadow} geometry={nodes.mesh980636007006.geometry} material={materials.Base} />
        <mesh name="mesh980636007006_1" castShadow={castShadow} geometry={nodes.mesh980636007006_1.geometry} material={materials.Primary} />
      </group>
      <group name="Vessel002" position={[-11.814, 1.375, -72.591]} rotation={[-Math.PI, 0.294, -Math.PI]}>
        <mesh name="mesh980636007010" castShadow={castShadow} geometry={nodes.mesh980636007010.geometry} material={materials.Base} />
        <mesh name="mesh980636007010_1" castShadow={castShadow} geometry={nodes.mesh980636007010_1.geometry} material={materials.Primary} />
      </group>

    </group>
  )
}

useGLTF.preload('./models/BlueSkyMap.glb')
