//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/model/car/Car Hatchback.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props: {
  scale?: number
  position?: [number, number, number]
  rotation?: [number, number, number]
}) {
  const { nodes, materials } = useGLTF('./models/car/Car Hatchback.glb')
  return (
    <group {...props} dispose={null} castShadow receiveShadow>
      <mesh geometry={nodes.car_hatchback.geometry} material={materials.citybits_texture} rotation={[-Math.PI / 2, 0, 0]} scale={100} castShadow receiveShadow>
        <mesh geometry={nodes.car_hatchback_wheel_front_left.geometry} material={materials.citybits_texture} position={[0.002, -0.0025, 0]} castShadow receiveShadow />
        <mesh geometry={nodes.car_hatchback_wheel_rear_left.geometry} material={materials.citybits_texture} position={[0.002, 0.0025, 0]} castShadow receiveShadow />
        <mesh geometry={nodes.car_hatchback_wheel_front_right.geometry} material={materials.citybits_texture} position={[-0.002, -0.0025, 0]} castShadow receiveShadow />
        <mesh geometry={nodes.car_hatchback_wheel_rear_right.geometry} material={materials.citybits_texture} position={[-0.002, 0.0025, 0]} castShadow receiveShadow />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/car/Car Hatchback.glb')
