//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/island.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Physics, RigidBody } from '@react-three/rapier'

export function Island(props: any) {
  const { nodes, materials } = useGLTF('./island.glb')
  return (
    <group {...props} dispose={null} receiveShadow castShadow>
      <Physics gravity={[0, -10, 0]} >
        <mesh geometry={nodes.Island.geometry} position={[0.347, 8.591, 0]} scale={0.795} receiveShadow castShadow >
          <meshStandardMaterial color={"#99532b"} />
        </mesh>

        <mesh geometry={nodes.I.geometry} material={nodes.I.material} position={[19.092, 3.972, 36.233]} rotation={[Math.PI / 2, 0, -0.188]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.N.geometry} material={nodes.N.material} position={[24.109, 4.06, 35.277]} rotation={[Math.PI / 2, 0, -0.188]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.O.geometry} material={nodes.O.material} position={[21.155, 4.048, 35.935]} rotation={[Math.PI / 2, 0, -0.188]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.S.geometry} material={nodes.S.material} position={[26.884, 4.094, 34.748]} rotation={[Math.PI / 2, 0, -0.188]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text003.geometry} material={nodes.Text003.material} position={[17.139, 4.304, 36.605]} rotation={[Math.PI / 2, 0, -0.188]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text004.geometry} material={nodes.Text004.material} position={[14.732, 3.567, 37.063]} rotation={[Math.PI / 2, 0, -0.188]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text005.geometry} material={nodes.Text005.material} position={[11.962, 3.952, 37.591]} rotation={[Math.PI / 2, 0, -0.188]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text006.geometry} material={nodes.Text006.material} position={[9.521, 4.373, 37.987]} rotation={[Math.PI / 2, 0, 0.085]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text007.geometry} material={nodes.Text007.material} position={[6.258, 4.034, 37.709]} rotation={[Math.PI / 2, 0, 0.085]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text008.geometry} material={nodes.Text008.material} position={[2.921, 4.278, 37.424]} rotation={[Math.PI / 2, 0, 0.085]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text009.geometry} material={nodes.Text009.material} position={[-0.217, 3.994, 37.156]} rotation={[Math.PI / 2, 0, 0.085]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text010.geometry} material={nodes.Text010.material} position={[-2.903, 4.037, 36.927]} rotation={[Math.PI / 2, 0, 0.085]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text011.geometry} material={nodes.Text011.material} position={[-5.345, 4.026, 36.718]} rotation={[Math.PI / 2, 0, 0.085]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text012.geometry} material={nodes.Text012.material} position={[-8.414, 3.478, 36.346]} rotation={[Math.PI / 2, 0, 0.256]} scale={4.036} receiveShadow castShadow />
        <mesh geometry={nodes.Text013.geometry} material={nodes.Text013.material} position={[-10.902, 3.857, 35.694]} rotation={[Math.PI / 2, 0, 0.256]} scale={4.036} receiveShadow castShadow />

        <mesh geometry={nodes.Text014.geometry} material={nodes.Text014.material} position={[-12.764, 4.236, 35.207]} rotation={[Math.PI / 2, 0, 0.256]} scale={4.036} receiveShadow castShadow />
      </Physics>
    </group>
  )
}

useGLTF.preload('./island.glb')
