// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/car/Bus.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Bus(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/vehicles/Bus.glb')
  console.log('animations', animations)
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    console.log('actions', actions, names)
    actions["Bus"].play()
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Bus004" position={[-8.313, 0.827, -9.488]}>
          <mesh name="Plane124" geometry={nodes.Plane124.geometry} material={materials.Primary} castShadow />
          <mesh name="Plane124_1" geometry={nodes.Plane124_1.geometry} material={materials.Base} castShadow />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/vehicles/Bus.glb')
