/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/vehicles/Bus.glb -o src/components/models/vehicles/Bus.tsx -r public/ 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane018: THREE.Mesh
    Plane018_1: THREE.Mesh
  }
  materials: {
    Primary: THREE.MeshStandardMaterial
    Base: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'BusTravel001'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Bus(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/vehicles/Bus.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['BusTravel001'].play()
    return () => {
      actions['BusTravel001'].stop()
    }
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Bus" position={[-7.08, 0.619, -16.216]} rotation={[0, -0.009, 0]} scale={2.079}>
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials.Primary} castShadow />
          <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials.Base} castShadow />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/vehicles/Bus.glb')
