/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/beach/Beach.glb -o src/components/models/beach/Beach.tsx -r public/ -s 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useUserContext } from '@/context/UserContext'

type GLTFResult = GLTF & {
  nodes: {
    boat: THREE.Mesh
    boat001: THREE.Mesh
    boat002: THREE.Mesh
    boat003: THREE.Mesh
    Plane287: THREE.Mesh
    Plane287_1: THREE.Mesh
    Plane095: THREE.Mesh
    Plane095_1: THREE.Mesh
    Plane303: THREE.Mesh
    Plane303_1: THREE.Mesh
    Road001: THREE.Mesh
    boat004: THREE.Mesh
    WindMill009: THREE.Mesh
    WindMillTurbin010: THREE.Mesh
    WindMill010: THREE.Mesh
    WindMillTurbin011: THREE.Mesh
    WindMill011: THREE.Mesh
    WindMillTurbin012: THREE.Mesh
    Plane314: THREE.Mesh
    Plane314_1: THREE.Mesh
    Plane314_2: THREE.Mesh
    Plane317: THREE.Mesh
    Plane317_1: THREE.Mesh
    Plane317_2: THREE.Mesh
    Plane319: THREE.Mesh
    Plane319_1: THREE.Mesh
    Plane319_2: THREE.Mesh
    Plane320: THREE.Mesh
    Plane320_1: THREE.Mesh
    Plane320_2: THREE.Mesh
    Plane321: THREE.Mesh
    Plane321_1: THREE.Mesh
    Plane321_2: THREE.Mesh
    Plane322: THREE.Mesh
    Plane322_1: THREE.Mesh
    Plane322_2: THREE.Mesh
    Plane323: THREE.Mesh
    Plane323_1: THREE.Mesh
    Plane323_2: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Plane158: THREE.Mesh
    Plane158_1: THREE.Mesh
    Plane326: THREE.Mesh
    Plane326_1: THREE.Mesh
    Plane327: THREE.Mesh
    Plane327_1: THREE.Mesh
    Plane327_2: THREE.Mesh
    Plane328: THREE.Mesh
    Plane328_1: THREE.Mesh
    Plane328_2: THREE.Mesh
    SurfingBoard: THREE.Mesh
    SurfingBoard001: THREE.Mesh
    Plane027: THREE.Mesh
    Plane027_1: THREE.Mesh
    Plane027_2: THREE.Mesh
    Plane077: THREE.Mesh
    Plane077_1: THREE.Mesh
    Plane077_2: THREE.Mesh
    Plane079: THREE.Mesh
    Plane079_1: THREE.Mesh
    Plane080: THREE.Mesh
    Plane080_1: THREE.Mesh
    Plane093: THREE.Mesh
    Plane093_1: THREE.Mesh
    Plane096: THREE.Mesh
    Plane096_1: THREE.Mesh
    Plane097: THREE.Mesh
    Plane097_1: THREE.Mesh
    Plane098: THREE.Mesh
    Plane098_1: THREE.Mesh
    Plane100: THREE.Mesh
    Plane100_1: THREE.Mesh
    Plane101: THREE.Mesh
    Plane101_1: THREE.Mesh
    Plane104: THREE.Mesh
    Plane104_1: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    CoconutTree: THREE.MeshStandardMaterial
    Tree: THREE.MeshStandardMaterial
    Primary: THREE.MeshStandardMaterial
    ['Grass.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'WindMilTurbin.001' | 'WindMilTurbin.011' | 'WindMilTurbin.012'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Beach(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/beach/Beach.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  const { quality } = useUserContext()


  useEffect(() => {
    // Menyimpan semua timeout IDs untuk dibersihkan nanti
    const timeouts = [];

    // Fungsi helper untuk menjadwalkan animasi dengan delay
    const scheduleAnimation = (actionName: string) => {
      const delay = Math.floor(Math.random() * 800);
      const timeoutId = setTimeout(() => {
        actions[actionName]?.play();
      }, delay);
      timeouts.push(timeoutId);
    };

    // Jadwalkan animasi dengan delay yang berbeda
    scheduleAnimation('WindMilTurbin.001'); // No delay for the first one
    scheduleAnimation('WindMilTurbin.011'); // Delay 100ms
    scheduleAnimation('WindMilTurbin.012');

    // Bersihkan timeout saat komponen di-unmount
    return () => {
      timeouts.forEach(clearTimeout);
      Object.values(actions).forEach(action => action.stop());
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="WindMill009" castShadow geometry={nodes.WindMill009.geometry} material={materials.Base} position={[42.254, -0.291, 80.966]} rotation={[-3.14, 0.602, -3.132]} scale={1.363}>
          <mesh name="WindMillTurbin010" castShadow geometry={nodes.WindMillTurbin010.geometry} material={materials.Base} position={[0.001, 2.724, 0.342]} />
        </mesh>
        {quality >= 1 &&
          <mesh name="WindMill010" castShadow geometry={nodes.WindMill010.geometry} material={materials.Base} position={[40.642, -0.244, 75.942]} rotation={[-3.14, 0.602, -3.132]} scale={1.363}>
            <mesh name="WindMillTurbin011" castShadow geometry={nodes.WindMillTurbin011.geometry} material={materials.Base} position={[0.001, 2.724, 0.342]} />
          </mesh>
        }
        {quality > 1 &&
          <mesh name="WindMill011" castShadow geometry={nodes.WindMill011.geometry} material={materials.Base} position={[46.014, -0.312, 79.633]} rotation={[-3.14, 0.602, -3.132]} scale={1.363}>
            <mesh name="WindMillTurbin012" castShadow geometry={nodes.WindMillTurbin012.geometry} material={materials.Base} position={[0.001, 2.724, 0.342]} />
          </mesh>
        }

        <mesh name="boat" castShadow geometry={nodes.boat.geometry} material={materials.Base} position={[3.274, -0.859, 74.756]} scale={1.528} />
        <mesh name="boat001" castShadow geometry={nodes.boat001.geometry} material={materials.Base} position={[13.667, -0.859, 83.746]} rotation={[0, 0.917, 0]} scale={1.202} />
        <mesh name="boat002" castShadow geometry={nodes.boat002.geometry} material={materials.Base} position={[-28.459, -0.859, 71.485]} scale={1.202} />
        <mesh name="boat003" castShadow geometry={nodes.boat003.geometry} material={materials.Base} position={[-26.255, -0.859, 70.002]} rotation={[0, Math.PI / 3, 0]} scale={1.202} />
        <group name="tree321" position={[-50.283, -0.788, 66.438]} scale={1.913}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree324" position={[24.154, -0.665, 72.229]} scale={1.801}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree327" position={[-24.648, -0.265, 59.499]} scale={1.817}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree330" position={[-29.159, -0.236, 59.673]} scale={1.935}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree333" position={[-30.614, -0.204, 59.619]} scale={1.885}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree336" position={[-17.013, -0.27, 58.537]} scale={1.725}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree339" position={[-6.643, -0.398, 58.65]} scale={1.783}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree342" position={[11.74, -0.557, 61.907]} scale={1.904}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree345" position={[-5.623, -0.423, 58.747]} scale={1.824}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree348" position={[20.635, -0.652, 62.767]} scale={1.733}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree351" position={[-8.413, -0.096, 58.61]} scale={1.868}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree354" position={[30.237, -0.096, 72.008]} scale={1.807}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree357" position={[32.738, -0.096, 76.166]} scale={1.847}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree360" position={[31.507, -0.103, 75.574]} scale={1.848}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree363" position={[-49.62, 1.564, 61.999]} scale={1.79}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree366" position={[-56.377, 0.637, 68.562]} scale={1.828}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree369" position={[26.522, -0.096, 63.796]} scale={1.757}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree372" position={[-46.593, -0.561, 63.972]} scale={1.763}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree375" position={[29.358, -0.148, 74.296]} scale={1.942}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree378" position={[25.798, -0.096, 66.59]} scale={1.951}>
          <mesh name="Plane287" castShadow geometry={nodes.Plane287.geometry} material={materials.CoconutTree} />
          <mesh name="Plane287_1" castShadow geometry={nodes.Plane287_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree322" position={[-26.172, -0.283, 59.684]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.744}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree325" position={[21.001, -0.597, 63.643]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.953}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree328" position={[-37.238, -0.23, 59.17]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.823}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree331" position={[-36.602, -0.498, 61.707]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.989}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree334" position={[-34.124, -0.207, 59.082]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.915}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree337" position={[-18.144, -0.315, 58.878]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.907}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree340" position={[22.189, -0.376, 64.852]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.839}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree343" position={[-33.36, -0.241, 59.782]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.84}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree346" position={[12.308, -0.466, 61.389]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.802}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree349" position={[-6.095, -0.2, 58.59]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.77}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree352" position={[24.766, -0.096, 67.11]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.992}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree355" position={[30.957, -0.096, 72.11]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.813}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree358" position={[-37.714, 0.332, 57.828]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.811}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree361" position={[31.316, -0.122, 75.236]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.931}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree364" position={[-51.624, -0.397, 64.829]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.947}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree367" position={[-56.007, 0.388, 68.519]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.984}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree370" position={[-55.425, -0.171, 69.042]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.858}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree373" position={[18.959, -0.666, 64.008]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={1.949}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree376" position={[29.911, -0.153, 74.656]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={2.019}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree379" position={[-49.116, 0.764, 62.559]} rotation={[-Math.PI, 0.427, -Math.PI]} scale={2.001}>
          <mesh name="Plane095" castShadow geometry={nodes.Plane095.geometry} material={materials.CoconutTree} />
          <mesh name="Plane095_1" castShadow geometry={nodes.Plane095_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree323" position={[24.74, -0.096, 64.803]} rotation={[0, -0.981, 0]} scale={1.976}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree326" position={[-29.806, -0.088, 57.744]} rotation={[0, -0.981, 0]} scale={1.989}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree329" position={[21.257, -0.8, 65.247]} rotation={[0, -0.981, 0]} scale={1.83}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree332" position={[-31.331, -0.378, 59.008]} rotation={[0, -0.981, 0]} scale={1.753}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree335" position={[-9.677, -0.146, 60.316]} rotation={[0, -0.981, 0]} scale={1.925}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree338" position={[23.815, -0.275, 69.299]} rotation={[0, -0.981, 0]} scale={1.96}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree341" position={[11.879, -0.411, 61.057]} rotation={[0, -0.981, 0]} scale={1.874}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree344" position={[-34.376, -0.313, 58.505]} rotation={[0, -0.981, 0]} scale={2.005}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree347" position={[-18.876, -0.207, 59.131]} rotation={[0, -0.981, 0]} scale={1.825}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree350" position={[18.058, -0.476, 63.084]} rotation={[0, -0.981, 0]} scale={1.887}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree353" position={[26.186, -0.096, 65.118]} rotation={[0, -0.981, 0]} scale={1.754}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree356" position={[35.092, -0.096, 80.401]} rotation={[0, -0.981, 0]} scale={1.944}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree359" position={[-54.825, -0.51, 66.992]} rotation={[0, -0.981, 0]} scale={1.835}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree362" position={[31.066, -0.146, 76.202]} rotation={[0, -0.981, 0]} scale={1.893}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree365" position={[-52.033, -0.18, 63.914]} rotation={[0, -0.981, 0]} scale={2.015}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree368" position={[-30.877, -0.085, 57.697]} rotation={[0, -0.981, 0]} scale={1.744}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree371" position={[23.676, -1.231, 73.35]} rotation={[0, -0.981, 0]} scale={1.896}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree374" position={[19.274, -0.575, 62.408]} rotation={[0, -0.981, 0]} scale={1.763}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree377" position={[31.206, -0.121, 74.999]} rotation={[0, -0.981, 0]} scale={1.976}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <group name="tree380" position={[-53.571, 1.436, 63.062]} rotation={[0, -0.981, 0]} scale={1.726}>
          <mesh name="Plane303" castShadow geometry={nodes.Plane303.geometry} material={materials.CoconutTree} />
          <mesh name="Plane303_1" castShadow geometry={nodes.Plane303_1.geometry} material={materials.Tree} />
        </group>
        <mesh name="boat004" castShadow geometry={nodes.boat004.geometry} material={materials.Base} position={[10.722, -0.859, 83.118]} rotation={[0, 0.917, 0]} scale={1.202} />

        <group name="BeachChairSet" position={[-6.552, -0.713, 63.408]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet007" position={[-8.273, -0.363, 61.471]} rotation={[0.166, 0, -0.009]} scale={0.266}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet008" position={[-33.636, -0.392, 61.498]} rotation={[0.159, 0, -0.01]} scale={0.274}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet009" position={[-17.194, -0.46, 61.362]} rotation={[0.163, 0, 0.02]} scale={0.274}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet001" position={[-31.745, -0.603, 63.427]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane317" castShadow geometry={nodes.Plane317.geometry} material={materials.Base} />
          <mesh name="Plane317_1" castShadow geometry={nodes.Plane317_1.geometry} material={materials.Primary} />
          <mesh name="Plane317_2" castShadow geometry={nodes.Plane317_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet002" position={[-10.026, -0.698, 63.411]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane319" castShadow geometry={nodes.Plane319.geometry} material={materials.Base} />
          <mesh name="Plane319_1" castShadow geometry={nodes.Plane319_1.geometry} material={materials.Primary} />
          <mesh name="Plane319_2" castShadow geometry={nodes.Plane319_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet003" position={[-35.687, -0.585, 63.43]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane320" castShadow geometry={nodes.Plane320.geometry} material={materials.Base} />
          <mesh name="Plane320_1" castShadow geometry={nodes.Plane320_1.geometry} material={materials.Primary} />
          <mesh name="Plane320_2" castShadow geometry={nodes.Plane320_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet004" position={[-37.842, -0.576, 63.431]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane321" castShadow geometry={nodes.Plane321.geometry} material={materials.Base} />
          <mesh name="Plane321_1" castShadow geometry={nodes.Plane321_1.geometry} material={materials.Primary} />
          <mesh name="Plane321_2" castShadow geometry={nodes.Plane321_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet005" position={[6.705, -0.772, 63.398]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane322" castShadow geometry={nodes.Plane322.geometry} material={materials.Base} />
          <mesh name="Plane322_1" castShadow geometry={nodes.Plane322_1.geometry} material={materials.Primary} />
          <mesh name="Plane322_2" castShadow geometry={nodes.Plane322_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet006" position={[3.947, -0.759, 63.4]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane323" castShadow geometry={nodes.Plane323.geometry} material={materials.Base} />
          <mesh name="Plane323_1" castShadow geometry={nodes.Plane323_1.geometry} material={materials.Primary} />
          <mesh name="Plane323_2" castShadow geometry={nodes.Plane323_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="Mercusuar" position={[-45.583, -0.502, 75.476]} scale={0.777}>
          <mesh name="Cylinder003" castShadow geometry={nodes.Cylinder003.geometry} material={materials.Base} />
          <mesh name="Cylinder003_1" castShadow geometry={nodes.Cylinder003_1.geometry} material={materials.Primary} />
        </group>
        <group name="Mercusuar002" position={[24.553, 1.14, 61.085]} scale={0.718}>
          <mesh name="Cylinder003" castShadow geometry={nodes.Cylinder003.geometry} material={materials.Base} />
          <mesh name="Cylinder003_1" castShadow geometry={nodes.Cylinder003_1.geometry} material={materials.Primary} />
        </group>
        <group name="Mercusuar001" position={[60.245, -0.502, 84.119]} scale={0.777}>
          <mesh name="Cylinder004" castShadow geometry={nodes.Cylinder004.geometry} material={materials.Base} />
          <mesh name="Cylinder004_1" castShadow geometry={nodes.Cylinder004_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat001" position={[-3.597, -0.541, 69.004]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane158" castShadow geometry={nodes.Plane158.geometry} material={materials.Base} />
          <mesh name="Plane158_1" castShadow geometry={nodes.Plane158_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat002" position={[-6.561, -0.541, 69.463]} rotation={[0, 1.107, 0]}>
          <mesh name="Plane326" castShadow geometry={nodes.Plane326.geometry} material={materials.Base} />
          <mesh name="Plane326_1" castShadow geometry={nodes.Plane326_1.geometry} material={materials.Primary} />
        </group>
        <group name="SafetyGuardTower002" position={[-22.056, -0.568, 60.539]} scale={0.588}>
          <mesh name="Plane327" castShadow geometry={nodes.Plane327.geometry} material={materials.Base} />
          <mesh name="Plane327_1" castShadow geometry={nodes.Plane327_1.geometry} material={materials.Primary} />
          <mesh name="Plane327_2" castShadow geometry={nodes.Plane327_2.geometry} material={materials.CoconutTree} />
        </group>
        <group name="SafetyGuardTower001" position={[9.269, -0.568, 60.539]} scale={0.588}>
          <mesh name="Plane328" castShadow geometry={nodes.Plane328.geometry} material={materials.Base} />
          <mesh name="Plane328_1" castShadow geometry={nodes.Plane328_1.geometry} material={materials.Primary} />
          <mesh name="Plane328_2" castShadow geometry={nodes.Plane328_2.geometry} material={materials.CoconutTree} />
        </group>
        <mesh name="SurfingBoard" castShadow geometry={nodes.SurfingBoard.geometry} material={materials.Base} position={[-21.625, -0.095, 61.403]} rotation={[1.434, 0, 0.01]} scale={0.566} />
        <mesh name="SurfingBoard001" castShadow geometry={nodes.SurfingBoard001.geometry} material={materials.Base} position={[8.847, -0.052, 61.717]} rotation={[1.434, 0, 0.01]} scale={0.566} />
        <group name="BeachStore" position={[17.681, 2.035, 61.604]} scale={0.202}>
          <mesh name="Plane027" castShadow geometry={nodes.Plane027.geometry} material={materials.Base} />
          <mesh name="Plane027_1" castShadow geometry={nodes.Plane027_1.geometry} material={materials.Primary} />
          <mesh name="Plane027_2" castShadow geometry={nodes.Plane027_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachStore001" position={[20.683, 2.035, 61.604]} scale={0.202}>
          <mesh name="Plane077" castShadow geometry={nodes.Plane077.geometry} material={materials.Base} />
          <mesh name="Plane077_1" castShadow geometry={nodes.Plane077_1.geometry} material={materials.Primary} />
          <mesh name="Plane077_2" castShadow geometry={nodes.Plane077_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="FoodTruck" position={[4.167, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane079" castShadow geometry={nodes.Plane079.geometry} material={materials.Primary} />
          <mesh name="Plane079_1" castShadow geometry={nodes.Plane079_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck001" position={[6.543, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane080" castShadow geometry={nodes.Plane080.geometry} material={materials.Primary} />
          <mesh name="Plane080_1" castShadow geometry={nodes.Plane080_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck002" position={[-15.192, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane093" castShadow geometry={nodes.Plane093.geometry} material={materials.Primary} />
          <mesh name="Plane093_1" castShadow geometry={nodes.Plane093_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck003" position={[-13.126, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane096" castShadow geometry={nodes.Plane096.geometry} material={materials.Primary} />
          <mesh name="Plane096_1" castShadow geometry={nodes.Plane096_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck004" position={[-11.147, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane097" castShadow geometry={nodes.Plane097.geometry} material={materials.Primary} />
          <mesh name="Plane097_1" castShadow geometry={nodes.Plane097_1.geometry} material={materials.Base} />
        </group>
        <group name="BeachHall" position={[-1.551, -0.74, 59.802]} scale={0.811}>
          <mesh name="Plane098" castShadow geometry={nodes.Plane098.geometry} material={materials.Base} />
          <mesh name="Plane098_1" castShadow geometry={nodes.Plane098_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat003" position={[-39.027, -0.541, 69.443]} rotation={[-Math.PI, 1.396, -Math.PI]}>
          <mesh name="Plane100" castShadow geometry={nodes.Plane100.geometry} material={materials.Base} />
          <mesh name="Plane100_1" castShadow geometry={nodes.Plane100_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat004" position={[-37.947, -0.541, 75.567]} rotation={[-Math.PI, 1.396, -Math.PI]}>
          <mesh name="Plane101" castShadow geometry={nodes.Plane101.geometry} material={materials.Base} />
          <mesh name="Plane101_1" castShadow geometry={nodes.Plane101_1.geometry} material={materials.Primary} />
        </group>
        <group name="BeachHall001" position={[-42.222, -0.74, 63.076]} rotation={[0, 0.124, 0]} scale={0.811}>
          <mesh name="Plane104" castShadow geometry={nodes.Plane104.geometry} material={materials.Base} />
          <mesh name="Plane104_1" castShadow geometry={nodes.Plane104_1.geometry} material={materials.Primary} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/beach/Beach.glb')
