/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/beach/Beach.glb -o src/components/models/beach/Beach.tsx -r public/ -s 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useUserContext } from '@/hooks/UserContext'

type GLTFResult = GLTF & {
  nodes: {
    boat: THREE.Mesh
    boat001: THREE.Mesh
    boat002: THREE.Mesh
    boat003: THREE.Mesh
    Plane287: THREE.Mesh
    Plane287_1: THREE.Mesh
    Plane095: THREE.Mesh
    Plane095_1: THREE.Mesh
    Plane303: THREE.Mesh
    Plane303_1: THREE.Mesh
    Road001: THREE.Mesh
    boat004: THREE.Mesh
    WindMill009: THREE.Mesh
    WindMillTurbin010: THREE.Mesh
    WindMill010: THREE.Mesh
    WindMillTurbin011: THREE.Mesh
    WindMill011: THREE.Mesh
    WindMillTurbin012: THREE.Mesh
    Plane314: THREE.Mesh
    Plane314_1: THREE.Mesh
    Plane314_2: THREE.Mesh
    Plane317: THREE.Mesh
    Plane317_1: THREE.Mesh
    Plane317_2: THREE.Mesh
    Plane319: THREE.Mesh
    Plane319_1: THREE.Mesh
    Plane319_2: THREE.Mesh
    Plane320: THREE.Mesh
    Plane320_1: THREE.Mesh
    Plane320_2: THREE.Mesh
    Plane321: THREE.Mesh
    Plane321_1: THREE.Mesh
    Plane321_2: THREE.Mesh
    Plane322: THREE.Mesh
    Plane322_1: THREE.Mesh
    Plane322_2: THREE.Mesh
    Plane323: THREE.Mesh
    Plane323_1: THREE.Mesh
    Plane323_2: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Plane158: THREE.Mesh
    Plane158_1: THREE.Mesh
    Plane326: THREE.Mesh
    Plane326_1: THREE.Mesh
    Plane327: THREE.Mesh
    Plane327_1: THREE.Mesh
    Plane327_2: THREE.Mesh
    Plane328: THREE.Mesh
    Plane328_1: THREE.Mesh
    Plane328_2: THREE.Mesh
    SurfingBoard: THREE.Mesh
    SurfingBoard001: THREE.Mesh
    Plane027: THREE.Mesh
    Plane027_1: THREE.Mesh
    Plane027_2: THREE.Mesh
    Plane077: THREE.Mesh
    Plane077_1: THREE.Mesh
    Plane077_2: THREE.Mesh
    Plane079: THREE.Mesh
    Plane079_1: THREE.Mesh
    Plane080: THREE.Mesh
    Plane080_1: THREE.Mesh
    Plane093: THREE.Mesh
    Plane093_1: THREE.Mesh
    Plane096: THREE.Mesh
    Plane096_1: THREE.Mesh
    Plane097: THREE.Mesh
    Plane097_1: THREE.Mesh
    Plane098: THREE.Mesh
    Plane098_1: THREE.Mesh
    Plane100: THREE.Mesh
    Plane100_1: THREE.Mesh
    Plane101: THREE.Mesh
    Plane101_1: THREE.Mesh
    Plane104: THREE.Mesh
    Plane104_1: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    CoconutTree: THREE.MeshStandardMaterial
    Tree: THREE.MeshStandardMaterial
    Primary: THREE.MeshStandardMaterial
    ['Grass.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'WindMilTurbin.001' | 'WindMilTurbin.011' | 'WindMilTurbin.012'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Beach(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/beach/Beach.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  const { quality } = useUserContext()


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="boat" castShadow geometry={nodes.boat.geometry} material={materials.Base} position={[3.274, -0.859, 74.756]} scale={1.528} />
        <mesh name="boat001" castShadow geometry={nodes.boat001.geometry} material={materials.Base} position={[13.667, -0.859, 83.746]} rotation={[0, 0.917, 0]} scale={1.202} />
        <mesh name="boat002" castShadow geometry={nodes.boat002.geometry} material={materials.Base} position={[-28.459, -0.859, 71.485]} scale={1.202} />
        <mesh name="boat003" castShadow geometry={nodes.boat003.geometry} material={materials.Base} position={[-26.255, -0.859, 70.002]} rotation={[0, Math.PI / 3, 0]} scale={1.202} />

        <mesh name="boat004" castShadow geometry={nodes.boat004.geometry} material={materials.Base} position={[10.722, -0.859, 83.118]} rotation={[0, 0.917, 0]} scale={1.202} />

        <group name="BeachChairSet" position={[-6.552, -0.713, 63.408]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet007" position={[-8.273, -0.363, 61.471]} rotation={[0.166, 0, -0.009]} scale={0.266}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet008" position={[-33.636, -0.392, 61.498]} rotation={[0.159, 0, -0.01]} scale={0.274}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet009" position={[-17.194, -0.46, 61.362]} rotation={[0.163, 0, 0.02]} scale={0.274}>
          <mesh name="Plane314" castShadow geometry={nodes.Plane314.geometry} material={materials.Base} />
          <mesh name="Plane314_1" castShadow geometry={nodes.Plane314_1.geometry} material={materials.Primary} />
          <mesh name="Plane314_2" castShadow geometry={nodes.Plane314_2.geometry} material={materials.Primary} />
        </group>
        <group name="BeachChairSet001" position={[-31.745, -0.603, 63.427]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane317" castShadow geometry={nodes.Plane317.geometry} material={materials.Base} />
          <mesh name="Plane317_1" castShadow geometry={nodes.Plane317_1.geometry} material={materials.Primary} />
          <mesh name="Plane317_2" castShadow geometry={nodes.Plane317_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet002" position={[-10.026, -0.698, 63.411]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane319" castShadow geometry={nodes.Plane319.geometry} material={materials.Base} />
          <mesh name="Plane319_1" castShadow geometry={nodes.Plane319_1.geometry} material={materials.Primary} />
          <mesh name="Plane319_2" castShadow geometry={nodes.Plane319_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet003" position={[-35.687, -0.585, 63.43]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane320" castShadow geometry={nodes.Plane320.geometry} material={materials.Base} />
          <mesh name="Plane320_1" castShadow geometry={nodes.Plane320_1.geometry} material={materials.Primary} />
          <mesh name="Plane320_2" castShadow geometry={nodes.Plane320_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet004" position={[-37.842, -0.576, 63.431]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane321" castShadow geometry={nodes.Plane321.geometry} material={materials.Base} />
          <mesh name="Plane321_1" castShadow geometry={nodes.Plane321_1.geometry} material={materials.Primary} />
          <mesh name="Plane321_2" castShadow geometry={nodes.Plane321_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet005" position={[6.705, -0.772, 63.398]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane322" castShadow geometry={nodes.Plane322.geometry} material={materials.Base} />
          <mesh name="Plane322_1" castShadow geometry={nodes.Plane322_1.geometry} material={materials.Primary} />
          <mesh name="Plane322_2" castShadow geometry={nodes.Plane322_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachChairSet006" position={[3.947, -0.759, 63.4]} rotation={[0.169, 0, -0.004]} scale={0.261}>
          <mesh name="Plane323" castShadow geometry={nodes.Plane323.geometry} material={materials.Base} />
          <mesh name="Plane323_1" castShadow geometry={nodes.Plane323_1.geometry} material={materials.Primary} />
          <mesh name="Plane323_2" castShadow geometry={nodes.Plane323_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="Mercusuar" position={[-45.583, -0.502, 75.476]} scale={0.777}>
          <mesh name="Cylinder003" castShadow geometry={nodes.Cylinder003.geometry} material={materials.Base} />
          <mesh name="Cylinder003_1" castShadow geometry={nodes.Cylinder003_1.geometry} material={materials.Primary} />
        </group>
        <group name="Mercusuar002" position={[24.553, 1.14, 61.085]} scale={0.718}>
          <mesh name="Cylinder003" castShadow geometry={nodes.Cylinder003.geometry} material={materials.Base} />
          <mesh name="Cylinder003_1" castShadow geometry={nodes.Cylinder003_1.geometry} material={materials.Primary} />
        </group>
        <group name="Mercusuar001" position={[60.245, -0.502, 84.119]} scale={0.777}>
          <mesh name="Cylinder004" castShadow geometry={nodes.Cylinder004.geometry} material={materials.Base} />
          <mesh name="Cylinder004_1" castShadow geometry={nodes.Cylinder004_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat001" position={[-3.597, -0.541, 69.004]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Plane158" castShadow geometry={nodes.Plane158.geometry} material={materials.Base} />
          <mesh name="Plane158_1" castShadow geometry={nodes.Plane158_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat002" position={[-6.561, -0.541, 69.463]} rotation={[0, 1.107, 0]}>
          <mesh name="Plane326" castShadow geometry={nodes.Plane326.geometry} material={materials.Base} />
          <mesh name="Plane326_1" castShadow geometry={nodes.Plane326_1.geometry} material={materials.Primary} />
        </group>
        <group name="SafetyGuardTower002" position={[-22.056, -0.568, 60.539]} scale={0.588}>
          <mesh name="Plane327" castShadow geometry={nodes.Plane327.geometry} material={materials.Base} />
          <mesh name="Plane327_1" castShadow geometry={nodes.Plane327_1.geometry} material={materials.Primary} />
          <mesh name="Plane327_2" castShadow geometry={nodes.Plane327_2.geometry} material={materials.CoconutTree} />
        </group>
        <group name="SafetyGuardTower001" position={[9.269, -0.568, 60.539]} scale={0.588}>
          <mesh name="Plane328" castShadow geometry={nodes.Plane328.geometry} material={materials.Base} />
          <mesh name="Plane328_1" castShadow geometry={nodes.Plane328_1.geometry} material={materials.Primary} />
          <mesh name="Plane328_2" castShadow geometry={nodes.Plane328_2.geometry} material={materials.CoconutTree} />
        </group>
        <mesh name="SurfingBoard" castShadow geometry={nodes.SurfingBoard.geometry} material={materials.Base} position={[-21.625, -0.095, 61.403]} rotation={[1.434, 0, 0.01]} scale={0.566} />
        <mesh name="SurfingBoard001" castShadow geometry={nodes.SurfingBoard001.geometry} material={materials.Base} position={[8.847, -0.052, 61.717]} rotation={[1.434, 0, 0.01]} scale={0.566} />
        <group name="BeachStore" position={[17.681, 2.035, 61.604]} scale={0.202}>
          <mesh name="Plane027" castShadow geometry={nodes.Plane027.geometry} material={materials.Base} />
          <mesh name="Plane027_1" castShadow geometry={nodes.Plane027_1.geometry} material={materials.Primary} />
          <mesh name="Plane027_2" castShadow geometry={nodes.Plane027_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="BeachStore001" position={[20.683, 2.035, 61.604]} scale={0.202}>
          <mesh name="Plane077" castShadow geometry={nodes.Plane077.geometry} material={materials.Base} />
          <mesh name="Plane077_1" castShadow geometry={nodes.Plane077_1.geometry} material={materials.Primary} />
          <mesh name="Plane077_2" castShadow geometry={nodes.Plane077_2.geometry} material={materials['Grass.001']} />
        </group>
        <group name="FoodTruck" position={[4.167, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane079" castShadow geometry={nodes.Plane079.geometry} material={materials.Primary} />
          <mesh name="Plane079_1" castShadow geometry={nodes.Plane079_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck001" position={[6.543, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane080" castShadow geometry={nodes.Plane080.geometry} material={materials.Primary} />
          <mesh name="Plane080_1" castShadow geometry={nodes.Plane080_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck002" position={[-15.192, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane093" castShadow geometry={nodes.Plane093.geometry} material={materials.Primary} />
          <mesh name="Plane093_1" castShadow geometry={nodes.Plane093_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck003" position={[-13.126, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane096" castShadow geometry={nodes.Plane096.geometry} material={materials.Primary} />
          <mesh name="Plane096_1" castShadow geometry={nodes.Plane096_1.geometry} material={materials.Base} />
        </group>
        <group name="FoodTruck004" position={[-11.147, 0.37, 57.749]} rotation={[0, -Math.PI / 2, 0]} scale={[0.579, 0.678, 0.678]}>
          <mesh name="Plane097" castShadow geometry={nodes.Plane097.geometry} material={materials.Primary} />
          <mesh name="Plane097_1" castShadow geometry={nodes.Plane097_1.geometry} material={materials.Base} />
        </group>
        <group name="BeachHall" position={[-1.551, -0.74, 59.802]} scale={0.811}>
          <mesh name="Plane098" castShadow geometry={nodes.Plane098.geometry} material={materials.Base} />
          <mesh name="Plane098_1" castShadow geometry={nodes.Plane098_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat003" position={[-39.027, -0.541, 69.443]} rotation={[-Math.PI, 1.396, -Math.PI]}>
          <mesh name="Plane100" castShadow geometry={nodes.Plane100.geometry} material={materials.Base} />
          <mesh name="Plane100_1" castShadow geometry={nodes.Plane100_1.geometry} material={materials.Primary} />
        </group>
        <group name="SpeedBoat004" position={[-37.947, -0.541, 75.567]} rotation={[-Math.PI, 1.396, -Math.PI]}>
          <mesh name="Plane101" castShadow geometry={nodes.Plane101.geometry} material={materials.Base} />
          <mesh name="Plane101_1" castShadow geometry={nodes.Plane101_1.geometry} material={materials.Primary} />
        </group>
        <group name="BeachHall001" position={[-42.222, -0.74, 63.076]} rotation={[0, 0.124, 0]} scale={0.811}>
          <mesh name="Plane104" castShadow geometry={nodes.Plane104.geometry} material={materials.Base} />
          <mesh name="Plane104_1" castShadow geometry={nodes.Plane104_1.geometry} material={materials.Primary} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/beach/Beach.glb')
