/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scenes/Collaboration.glb -o src/components/models/scenes/Collaboration.tsx -k -s -r public/ 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane081: THREE.Mesh
    Plane081_1: THREE.Mesh
    Plane081_2: THREE.Mesh
    Plane081_3: THREE.Mesh
    Plane071: THREE.Mesh
    Plane071_1: THREE.Mesh
    Plane071_2: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    Primary: THREE.MeshStandardMaterial
    Coles: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Collaboration(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/scenes/Collaboration.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group name="Coles" position={[4.876, 1.06, 31.453]} rotation={[0, Math.PI / 2, 0]} scale={0.911}>
        <mesh name="Plane081" castShadow geometry={nodes.Plane081.geometry} material={materials.Base} />
        <mesh name="Plane081_1" castShadow geometry={nodes.Plane081_1.geometry} material={materials.Primary} />
        <mesh name="Plane081_2" castShadow geometry={nodes.Plane081_2.geometry} material={materials.Coles} />
        <mesh name="Plane081_3" castShadow geometry={nodes.Plane081_3.geometry} material={materials.Glass} />
      </group>
      <group name="IBM" position={[-14.17, 0.484, 31.278]} scale={[5.62, 7.668, 5.265]}>
        <mesh name="Plane071" castShadow geometry={nodes.Plane071.geometry} material={materials.Glass} />
        <mesh name="Plane071_1" castShadow geometry={nodes.Plane071_1.geometry} material={materials.Base} />
        <mesh name="Plane071_2" castShadow geometry={nodes.Plane071_2.geometry} material={materials.Primary} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/scenes/Collaboration.glb')
