/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scenes/Mining.glb -o src/components/models/scenes/Mining.tsx -s -k -r public/ 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useUserContext } from '@/hooks/UserContext'
import { materials } from '@/consts/materials'

type GLTFResult = GLTF & {
  nodes: {
    Plane256: THREE.Mesh
    Plane256_1: THREE.Mesh

    Plane257: THREE.Mesh
    Plane257_1: THREE.Mesh

    Plane315: THREE.Mesh
    Plane315_1: THREE.Mesh
    Plane316: THREE.Mesh
    Plane316_1: THREE.Mesh
    Plane263: THREE.Mesh
    Plane263_1: THREE.Mesh
    Plane255: THREE.Mesh
    Plane255_1: THREE.Mesh
    Plane255_2: THREE.Mesh
    Plane117: THREE.Mesh
    Plane117_1: THREE.Mesh
    Plane117_2: THREE.Mesh
    Plane218: THREE.Mesh
    Plane218_1: THREE.Mesh
    Plane219: THREE.Mesh
    Plane219_1: THREE.Mesh
    Plane259: THREE.Mesh
    Plane259_1: THREE.Mesh
    Plane336: THREE.Mesh
    Plane336_1: THREE.Mesh
  }
  materials: {
    Glass: THREE.MeshPhysicalMaterial
    Base: THREE.MeshStandardMaterial
    Primary: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Mining(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/scenes/Mining.glb') as GLTFResult
  const { isNight } = useUserContext()
  const glass = isNight ? materials.GlassNight : materials.Glass
  return (
    <group {...props} dispose={null}>
      <group name="Dump_Truck" position={[-60.858, 8.989, 28.118]} rotation={[-3.108, 1.047, 3.103]} scale={0.525}>
        <mesh name="Plane256" castShadow receiveShadow geometry={nodes.Plane256.geometry} material={glass} />
        <mesh name="Plane256_1" castShadow receiveShadow geometry={nodes.Plane256_1.geometry} material={materials.Base} />
      </group>
      <group name="Dump_Truck005" position={[-51.716, 4.684, 31.775]} rotation={[3.06, 1.054, -3.106]} scale={0.525}>
        <mesh name="Plane256" castShadow receiveShadow geometry={nodes.Plane256.geometry} material={glass} />
        <mesh name="Plane256_1" castShadow receiveShadow geometry={nodes.Plane256_1.geometry} material={materials.Base} />
      </group>
      <group name="Dump_Truck001" position={[-60.777, 8.99, 30.727]} rotation={[-3.108, 1.047, 3.103]} scale={0.525}>
        <mesh name="Plane257" castShadow receiveShadow geometry={nodes.Plane257.geometry} material={glass} />
        <mesh name="Plane257_1" castShadow receiveShadow geometry={nodes.Plane257_1.geometry} material={materials.Base} />
      </group>
      <group name="Dump_Truck002" position={[-60.953, 8.986, 33.633]} rotation={[-3.107, 1.047, 3.101]} scale={0.525}>
        <mesh name="Plane257" castShadow receiveShadow geometry={nodes.Plane257.geometry} material={glass} />
        <mesh name="Plane257_1" castShadow receiveShadow geometry={nodes.Plane257_1.geometry} material={materials.Base} />
      </group>
      <group name="Dump_Truck003" position={[-60.906, 8.989, 25.509]} rotation={[-3.109, 1.047, 3.103]} scale={0.525}>
        <mesh name="Plane257" castShadow receiveShadow geometry={nodes.Plane257.geometry} material={glass} />
        <mesh name="Plane257_1" castShadow receiveShadow geometry={nodes.Plane257_1.geometry} material={materials.Base} />
      </group>
      <group name="Dump_Truck006" position={[-51.904, 4.519, 34.26]} rotation={[-3.082, 1.085, 3.074]} scale={0.525}>
        <mesh name="Plane257" castShadow receiveShadow geometry={nodes.Plane257.geometry} material={glass} />
        <mesh name="Plane257_1" castShadow receiveShadow geometry={nodes.Plane257_1.geometry} material={materials.Base} />
      </group>
      <group name="Dump_Truck004" position={[-60.9, 8.988, 23.224]} rotation={[-3.108, 1.047, 3.103]} scale={0.525}>
        <mesh name="Plane315" castShadow receiveShadow geometry={nodes.Plane315.geometry} material={glass} />
        <mesh name="Plane315_1" castShadow receiveShadow geometry={nodes.Plane315_1.geometry} material={materials.Base} />
      </group>
      <group name="Dump_Truck007" position={[-51.617, 4.528, 29.176]} rotation={[-3.087, 1.053, 3.078]} scale={0.525}>
        <mesh name="Plane316" castShadow receiveShadow geometry={nodes.Plane316.geometry} material={glass} />
        <mesh name="Plane316_1" castShadow receiveShadow geometry={nodes.Plane316_1.geometry} material={materials.Base} />
      </group>
      <group name="Excavator" position={[-62.102, 9.054, 42.18]} rotation={[3.025, 1.089, -3.01]} scale={1.634}>
        <mesh name="Plane263" castShadow receiveShadow geometry={nodes.Plane263.geometry} material={materials.Base} />
        <mesh name="Plane263_1" castShadow receiveShadow geometry={nodes.Plane263_1.geometry} material={glass} />
      </group>
      <group name="Excavator002" position={[-52.192, 4.66, 43.151]} rotation={[-3.045, 1.062, 3.031]} scale={1.594}>
        <mesh name="Plane263" castShadow receiveShadow geometry={nodes.Plane263.geometry} material={materials.Base} />
        <mesh name="Plane263_1" castShadow receiveShadow geometry={nodes.Plane263_1.geometry} material={glass} />
      </group>
      <group name="Mining_Office" position={[-70.012, 14.01, 39.001]} rotation={[-1.571, 1.548, 1.571]} scale={0.825}>
        <mesh name="Plane255" castShadow receiveShadow geometry={nodes.Plane255.geometry} material={materials.Base} />
        <mesh name="Plane255_1" castShadow receiveShadow geometry={nodes.Plane255_1.geometry} material={glass} />
        <mesh name="Plane255_2" castShadow receiveShadow geometry={nodes.Plane255_2.geometry} material={materials.Base} />
      </group>
      <group name="Mining_Office001" position={[-70.018, 14.265, 34.332]} rotation={[-1.571, 1.548, 1.571]} scale={0.825}>
        <mesh name="Plane117" castShadow receiveShadow geometry={nodes.Plane117.geometry} material={materials.Base} />
        <mesh name="Plane117_1" castShadow receiveShadow geometry={nodes.Plane117_1.geometry} material={glass} />
        <mesh name="Plane117_2" castShadow receiveShadow geometry={nodes.Plane117_2.geometry} material={materials.Base} />
      </group>
      <group name="BaseCamp002" position={[-68.9, 14.332, 27.277]} rotation={[-Math.PI / 2, 1.548, Math.PI / 2]} scale={0.504}>
        <mesh name="Plane218" castShadow receiveShadow geometry={nodes.Plane218.geometry} material={materials.Primary} />
        <mesh name="Plane218_1" castShadow receiveShadow geometry={nodes.Plane218_1.geometry} material={materials.Base} />
      </group>
      <group name="BaseCamp001" position={[-72.148, 14.499, 27.277]} rotation={[-Math.PI / 2, 1.548, Math.PI / 2]} scale={0.504}>
        <mesh name="Plane219" castShadow receiveShadow geometry={nodes.Plane219.geometry} material={materials.Primary} />
        <mesh name="Plane219_1" castShadow receiveShadow geometry={nodes.Plane219_1.geometry} material={materials.Base} />
      </group>
      <group name="Excavator001" position={[-52.281, 4.656, 38.872]} rotation={[-3.045, 1.062, 3.031]} scale={1.594}>
        <mesh name="Plane259" castShadow receiveShadow geometry={nodes.Plane259.geometry} material={materials.Base} />
        <mesh name="Plane259_1" castShadow receiveShadow geometry={nodes.Plane259_1.geometry} material={glass} />
      </group>
      <group name="Dump_Truck008" position={[-51.403, 4.535, 26.319]} rotation={[-3.087, 1.053, 3.078]} scale={0.525}>
        <mesh name="Plane336" castShadow receiveShadow geometry={nodes.Plane336.geometry} material={glass} />
        <mesh name="Plane336_1" castShadow receiveShadow geometry={nodes.Plane336_1.geometry} material={materials.Base} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/scenes/Mining.glb')
