/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/texts/Text001.glb -o src/components/models/texts/Text001.tsx -r public/ 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Text001(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/texts/Text001.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={materials.Base} position={[-64.903, 9.534, -32.665]} castShadow />
    </group>
  )
}

useGLTF.preload('/models/texts/Text001.glb')
