// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/BlueSky.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useUserContext } from '@/context/UserContext';
import { materials } from '@/consts/materials';


export function Store(props) {
    const { nodes } = useGLTF('./models/BlueSkyMap.glb');
    const { isNight } = useUserContext()

    const glass = isNight ? materials.GlassNight : materials.Glass

    return (
        <group {...props} >

            <group name="Stand" position={[18.512, 0.862, 48.493]}>
                <mesh name="Plane049" castShadow geometry={nodes.Plane049.geometry} material={materials.Primary} />
                <mesh name="Plane049_1" castShadow geometry={nodes.Plane049_1.geometry} material={materials.Base} />
            </group>
            <group name="Stand008" position={[13.386, 0.862, 48.536]}>
                <mesh name="Plane049" castShadow geometry={nodes.Plane049.geometry} material={materials.Primary} />
                <mesh name="Plane049_1" castShadow geometry={nodes.Plane049_1.geometry} material={materials.Base} />
            </group>
            <mesh name="Stand001" castShadow geometry={nodes.Stand001.geometry} material={materials.Base} position={[18.518, 0.862, 50.613]} />
            <mesh name="Stand002" castShadow geometry={nodes.Stand002.geometry} material={materials.Base} position={[13.355, 0.862, 50.649]} />
            <mesh name="Stand005" castShadow geometry={nodes.Stand005.geometry} material={materials.Base} position={[18.397, 0.862, 42.058]} />
            <mesh name="Stand011" castShadow geometry={nodes.Stand011.geometry} material={materials.Base} position={[15.813, 0.862, 42.139]} />
            <mesh name="Stand003" castShadow geometry={nodes.Stand003.geometry} material={materials.Base} position={[20.448, 0.871, 50.691]} />
            <mesh name="Stand007" castShadow geometry={nodes.Stand007.geometry} material={materials.Base} position={[20.47, 0.871, 48.529]} />
            <mesh name="Stand009" castShadow geometry={nodes.Stand009.geometry} material={materials.Base} position={[16.612, 0.871, 50.638]} />
            <group name="Stand004" position={[11.207, -5.394, 47.03]}>
                <mesh name="Plane048" castShadow geometry={nodes.Plane048.geometry} material={materials.Primary} />
                <mesh name="Plane048_1" castShadow geometry={nodes.Plane048_1.geometry} material={materials.Base} />
            </group>
            <group name="Stand006" position={[20.423, 0.871, 42.11]}>
                <mesh name="Plane048" castShadow geometry={nodes.Plane048.geometry} material={materials.Primary} />
                <mesh name="Plane048_1" castShadow geometry={nodes.Plane048_1.geometry} material={materials.Base} />
            </group>
            <group name="Stand010" position={[15.237, 0.871, 50.585]}>
                <mesh name="Plane048" castShadow geometry={nodes.Plane048.geometry} material={materials.Primary} />
                <mesh name="Plane048_1" castShadow geometry={nodes.Plane048_1.geometry} material={materials.Base} />
            </group>
            <mesh name="Stand012" castShadow geometry={nodes.Stand012.geometry} material={materials.Base} position={[20.448, 0.871, 44.174]} />
            <mesh name="Stand015" castShadow geometry={nodes.Stand015.geometry} material={materials.Base} position={[16.612, 0.871, 44.12]} />
            <mesh name="Stand013" castShadow geometry={nodes.Stand013.geometry} material={materials.Base} position={[18.518, 0.862, 44.096]} />
            <mesh name="Stand014" castShadow geometry={nodes.Stand014.geometry} material={materials.Base} position={[13.355, 0.862, 44.132]} />
            <group name="Stand016" position={[15.237, 0.871, 44.068]}>
                <mesh name="Plane239" castShadow geometry={nodes.Plane239.geometry} material={materials.Primary} />
                <mesh name="Plane239_1" castShadow geometry={nodes.Plane239_1.geometry} material={materials.Base} />
            </group>
            <mesh name="Stand017" castShadow geometry={nodes.Stand017.geometry} material={materials.Base} position={[16.565, 0.871, 48.609]} />
            <group name="Stand018" position={[15.189, 0.871, 48.557]}>
                <mesh name="Plane241" castShadow geometry={nodes.Plane241.geometry} material={materials.Primary} />
                <mesh name="Plane241_1" castShadow geometry={nodes.Plane241_1.geometry} material={materials.Base} />
            </group>
            <group name="Stand019" position={[13.386, 0.862, 42.186]}>
                <mesh name="Plane242" castShadow geometry={nodes.Plane242.geometry} material={materials.Primary} />
                <mesh name="Plane242_1" castShadow geometry={nodes.Plane242_1.geometry} material={materials.Base} />
            </group>
            <mesh name="Stand020" castShadow geometry={nodes.Stand020.geometry} material={materials.Base} position={[18.397, 0.862, 46.179]} />
            <mesh name="Stand022" castShadow geometry={nodes.Stand022.geometry} material={materials.Base} position={[15.813, 0.862, 46.26]} />
            <group name="Stand021" position={[20.423, 0.871, 46.231]}>
                <mesh name="Plane244" castShadow geometry={nodes.Plane244.geometry} material={materials.Primary} />
                <mesh name="Plane244_1" castShadow geometry={nodes.Plane244_1.geometry} material={materials.Base} />
            </group>
            <group name="Stand023" position={[13.386, 0.862, 46.307]}>
                <mesh name="Plane245" castShadow geometry={nodes.Plane245.geometry} material={materials.Primary} />
                <mesh name="Plane245_1" castShadow geometry={nodes.Plane245_1.geometry} material={materials.Base} />
            </group>


            <group name="Store" position={[3.774, 0.568, -23.958]} rotation={[0, Math.PI / 2, 0]} scale={0.75}>
                <mesh name="Plane141" castShadow geometry={nodes.Plane141.geometry} material={materials.Base} />
                <mesh name="Plane141_1" castShadow geometry={nodes.Plane141_1.geometry} material={glass} />
            </group>
            <group name="Store001" position={[3.774, 0.568, -17.371]} rotation={[0, Math.PI / 2, 0]} scale={0.75}>
                <mesh name="Plane148" castShadow geometry={nodes.Plane148.geometry} material={materials.Base} />
                <mesh name="Plane148_1" castShadow geometry={nodes.Plane148_1.geometry} material={glass} />
            </group>
            <group name="Store002" position={[19.352, 0.568, 17.426]} scale={0.611}>
                <mesh name="Plane160" castShadow geometry={nodes.Plane160.geometry} material={glass} />
                <mesh name="Plane160_1" castShadow geometry={nodes.Plane160_1.geometry} material={materials.Base} />
            </group>
            <group name="Store003" position={[3.829, 0.568, -14.092]} rotation={[0, Math.PI / 2, 0]} scale={0.611}>
                <mesh name="Plane150" castShadow geometry={nodes.Plane150.geometry} material={glass} />
                <mesh name="Plane150_1" castShadow geometry={nodes.Plane150_1.geometry} material={materials.Base} />
            </group>
            <group name="Store004" position={[-4.307, 0.568, -28.121]} rotation={[0, -Math.PI / 2, 0]} scale={0.75}>
                <mesh name="Plane161" castShadow geometry={nodes.Plane161.geometry} material={materials.Base} />
                <mesh name="Plane161_1" castShadow geometry={nodes.Plane161_1.geometry} material={glass} />
            </group>
            <group name="Store005" position={[-4.307, 0.568, -21.534]} rotation={[0, -Math.PI / 2, 0]} scale={0.75}>
                <mesh name="Plane162" castShadow geometry={nodes.Plane162.geometry} material={materials.Base} />
                <mesh name="Plane162_1" castShadow geometry={nodes.Plane162_1.geometry} material={glass} />
            </group>
            <group name="Store006" position={[-4.252, 0.568, -18.255]} rotation={[0, -Math.PI / 2, 0]} scale={0.611}>
                <mesh name="Plane163" castShadow geometry={nodes.Plane163.geometry} material={glass} />
                <mesh name="Plane163_1" castShadow geometry={nodes.Plane163_1.geometry} material={materials.Base} />
            </group>
            <group name="store_L" position={[11.591, 0.568, 30.554]} rotation={[0, -Math.PI / 2, 0]} scale={1.693}>
                <mesh name="Text" castShadow geometry={nodes.Text.geometry} material={materials.Base} />
                <mesh name="Text_1" castShadow geometry={nodes.Text_1.geometry} material={glass} />
            </group>
            <group name="store_L001" position={[1.793, 0.5, 17.42]} scale={1.971}>
                <mesh name="Text" castShadow geometry={nodes.Text.geometry} material={materials.Base} />
                <mesh name="Text_1" castShadow geometry={nodes.Text_1.geometry} material={glass} />
            </group>
            <group name="store_L002" position={[4.175, 0.568, -20.646]} rotation={[0, Math.PI / 2, 0]} scale={1.118}>
                <mesh name="Text" castShadow geometry={nodes.Text.geometry} material={materials.Base} />
                <mesh name="Text_1" castShadow geometry={nodes.Text_1.geometry} material={glass} />
            </group>
            <group name="store_L004" position={[19.142, 0.568, -8.075]} rotation={[0, Math.PI / 2, 0]} scale={1.473}>
                <mesh name="Text" castShadow geometry={nodes.Text.geometry} material={materials.Base} />
                <mesh name="Text_1" castShadow geometry={nodes.Text_1.geometry} material={glass} />
            </group>
            <group name="store_L003" position={[-3.906, 0.568, -24.809]} rotation={[0, -Math.PI / 2, 0]} scale={1.118}>
                <mesh name="Text001" castShadow geometry={nodes.Text001.geometry} material={materials.Base} />
                <mesh name="Text001_1" castShadow geometry={nodes.Text001_1.geometry} material={glass} />
            </group>
            <group name="store_L005" position={[10.741, 0.5, 11.587]} rotation={[Math.PI, 0, Math.PI]} scale={1.971}>
                <mesh name="Text002" castShadow geometry={nodes.Text002.geometry} material={materials.Base} />
                <mesh name="Text002_1" castShadow geometry={nodes.Text002_1.geometry} material={glass} />
            </group>
            <group name="store_M" position={[-4.344, 1.286, -14.518]} rotation={[0, -Math.PI / 2, 0]} scale={1.413}>
                <mesh name="Cube006" castShadow geometry={nodes.Cube006.geometry} material={materials.Base} />
                <mesh name="Cube006_1" castShadow geometry={nodes.Cube006_1.geometry} material={materials.Primary} />
            </group>
            <group name="store_M002" position={[-3.232, 0.5, 11.279]} rotation={[Math.PI, 0, Math.PI]}>
                <mesh name="Cube008" castShadow geometry={nodes.Cube008.geometry} material={materials.Base} />
                <mesh name="Cube008_1" castShadow geometry={nodes.Cube008_1.geometry} material={glass} />
            </group>
            <group name="store_S" position={[6.078, 1.533, 18.258]} scale={1.962}>
                <mesh name="Cube011" castShadow geometry={nodes.Cube011.geometry} material={materials.Primary} />
                <mesh name="Cube011_1" castShadow geometry={nodes.Cube011_1.geometry} material={materials.Base} />
            </group>
            <group name="store_S001" position={[16.304, 1.364, 2.21]} scale={1.538}>
                <mesh name="Cube011" castShadow geometry={nodes.Cube011.geometry} material={materials.Primary} />
                <mesh name="Cube011_1" castShadow geometry={nodes.Cube011_1.geometry} material={materials.Base} />
            </group>
        </group>
    )
}

useGLTF.preload('./models/BlueSkyMap.glb')
