/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/buildings/Stores.glb -o src/components/models/buildings/Stores.tsx -k -s -r public/ 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { materials } from '@/consts/materials'
import { useUserContext } from '@/context/UserContext'

type GLTFResult = GLTF & {
  nodes: {

    Text: THREE.Mesh
    Text_1: THREE.Mesh
    Text_2: THREE.Mesh

    Cube011: THREE.Mesh
    Cube011_1: THREE.Mesh
    Cube011_2: THREE.Mesh

    Plane343: THREE.Mesh
    Plane343_1: THREE.Mesh
    Plane343_2: THREE.Mesh

    Plane355: THREE.Mesh
    Plane355_1: THREE.Mesh
    Plane355_2: THREE.Mesh
    Plane356: THREE.Mesh
    Plane356_1: THREE.Mesh
    Cube009: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Cube010: THREE.Mesh
    Cube010_1: THREE.Mesh

    Plane049: THREE.Mesh
    Plane049_1: THREE.Mesh
    Stand001: THREE.Mesh
    Stand002: THREE.Mesh
    Stand005: THREE.Mesh
    Stand011: THREE.Mesh
    Stand003: THREE.Mesh
    Stand007: THREE.Mesh
    Stand009: THREE.Mesh

    Plane048: THREE.Mesh
    Plane048_1: THREE.Mesh
    Stand012: THREE.Mesh
    Stand015: THREE.Mesh
    Stand013: THREE.Mesh
    Stand014: THREE.Mesh
    Plane239: THREE.Mesh
    Plane239_1: THREE.Mesh
    Stand017: THREE.Mesh
    Plane241: THREE.Mesh
    Plane241_1: THREE.Mesh
    Plane242: THREE.Mesh
    Plane242_1: THREE.Mesh
    Stand020: THREE.Mesh
    Stand022: THREE.Mesh
    Plane244: THREE.Mesh
    Plane244_1: THREE.Mesh
    Plane245: THREE.Mesh
    Plane245_1: THREE.Mesh
    Plane318: THREE.Mesh
    Plane318_1: THREE.Mesh
    Plane318_2: THREE.Mesh
    Plane160: THREE.Mesh
    Plane160_1: THREE.Mesh
    Plane141: THREE.Mesh
    Plane141_1: THREE.Mesh
    Plane148: THREE.Mesh
    Plane148_1: THREE.Mesh
    Plane150: THREE.Mesh
    Plane150_1: THREE.Mesh
    Text002: THREE.Mesh
    Text002_1: THREE.Mesh
    Text002_2: THREE.Mesh
    Cube008: THREE.Mesh
    Cube008_1: THREE.Mesh
    Cube008_2: THREE.Mesh
    Plane161: THREE.Mesh
    Plane161_1: THREE.Mesh
    Plane162: THREE.Mesh
    Plane162_1: THREE.Mesh
    Plane163: THREE.Mesh
    Plane163_1: THREE.Mesh
    Text001: THREE.Mesh
    Text001_1: THREE.Mesh
    Text001_2: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    Primary: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    ['Base.001']: THREE.MeshStandardMaterial
    ['Primary.001']: THREE.MeshStandardMaterial
    Window: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Stores(props: {
  castShadow: boolean
}) {
  const { castShadow } = props
  const { nodes } = useGLTF('/models/buildings/Stores.glb') as GLTFResult

  const { isNight } = useUserContext()

  const glass = isNight ? materials.GlassNight : materials.Glass
  return (
    <group {...props} dispose={null}>
      <group name="store_L006" position={[44.51, 0.568, 69.875]} scale={1.868}>
        <mesh name="Text" castShadow={castShadow} geometry={nodes.Text.geometry} material={materials.Base} />
        <mesh name="Text_1" castShadow={castShadow} geometry={nodes.Text_1.geometry} material={materials.Primary} />
        <mesh name="Text_2" castShadow={castShadow} geometry={nodes.Text_2.geometry} material={glass} />
      </group>
      <group name="store_L" position={[11.591, 0.568, 30.554]} rotation={[0, -Math.PI / 2, 0]} scale={1.693}>
        <mesh name="Text" castShadow={castShadow} geometry={nodes.Text.geometry} material={materials.Base} />
        <mesh name="Text_1" castShadow={castShadow} geometry={nodes.Text_1.geometry} material={materials.Primary} />
        <mesh name="Text_2" castShadow={castShadow} geometry={nodes.Text_2.geometry} material={glass} />
      </group>
      <group name="store_L001" position={[1.793, 0.5, 17.42]} scale={1.971}>
        <mesh name="Text" castShadow={castShadow} geometry={nodes.Text.geometry} material={materials.Base} />
        <mesh name="Text_1" castShadow={castShadow} geometry={nodes.Text_1.geometry} material={materials.Primary} />
        <mesh name="Text_2" castShadow={castShadow} geometry={nodes.Text_2.geometry} material={glass} />
      </group>
      <group name="store_L002" position={[4.175, 0.568, -20.646]} rotation={[0, Math.PI / 2, 0]} scale={1.118}>
        <mesh name="Text" castShadow={castShadow} geometry={nodes.Text.geometry} material={materials.Base} />
        <mesh name="Text_1" castShadow={castShadow} geometry={nodes.Text_1.geometry} material={materials.Primary} />
        <mesh name="Text_2" castShadow={castShadow} geometry={nodes.Text_2.geometry} material={glass} />
      </group>
      <group name="store_L004" position={[19.142, 0.568, -8.075]} rotation={[0, Math.PI / 2, 0]} scale={1.473}>
        <mesh name="Text" castShadow={castShadow} geometry={nodes.Text.geometry} material={materials.Base} />
        <mesh name="Text_1" castShadow={castShadow} geometry={nodes.Text_1.geometry} material={materials.Primary} />
        <mesh name="Text_2" castShadow={castShadow} geometry={nodes.Text_2.geometry} material={glass} />
      </group>
      <group name="store_S002" position={[46.6, 0.568, 61.098]} rotation={[Math.PI, 0, Math.PI]} scale={2.12}>
        <mesh name="Cube011" castShadow={castShadow} geometry={nodes.Cube011.geometry} material={materials.Primary} />
        <mesh name="Cube011_1" castShadow={castShadow} geometry={nodes.Cube011_1.geometry} material={materials.Base} />
        <mesh name="Cube011_2" castShadow={castShadow} geometry={nodes.Cube011_2.geometry} material={glass} />
      </group>
      <group name="store_S" position={[6.078, 0.434, 18.258]} scale={1.962}>
        <mesh name="Cube011" castShadow={castShadow} geometry={nodes.Cube011.geometry} material={materials.Primary} />
        <mesh name="Cube011_1" castShadow={castShadow} geometry={nodes.Cube011_1.geometry} material={materials.Base} />
        <mesh name="Cube011_2" castShadow={castShadow} geometry={nodes.Cube011_2.geometry} material={glass} />
      </group>
      <group name="store_S001" position={[16.304, 0.568, 2.21]} scale={1.538}>
        <mesh name="Cube011" castShadow={castShadow} geometry={nodes.Cube011.geometry} material={materials.Primary} />
        <mesh name="Cube011_1" castShadow={castShadow} geometry={nodes.Cube011_1.geometry} material={materials.Base} />
        <mesh name="Cube011_2" castShadow={castShadow} geometry={nodes.Cube011_2.geometry} material={glass} />
      </group>
      <group name="Store007" position={[44.664, 0.568, 42.855]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="Plane343" castShadow={castShadow} geometry={nodes.Plane343.geometry} material={materials.Base} />
        <mesh name="Plane343_1" castShadow={castShadow} geometry={nodes.Plane343_1.geometry} material={materials.Primary} />
        <mesh name="Plane343_2" castShadow={castShadow} geometry={nodes.Plane343_2.geometry} material={glass} />
      </group>
      <group name="Store010" position={[58.586, 0.568, 65.124]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="Plane343" castShadow={castShadow} geometry={nodes.Plane343.geometry} material={materials.Base} />
        <mesh name="Plane343_1" castShadow={castShadow} geometry={nodes.Plane343_1.geometry} material={materials.Primary} />
        <mesh name="Plane343_2" castShadow={castShadow} geometry={nodes.Plane343_2.geometry} material={glass} />
      </group>
      <group name="Store011" position={[73.601, 0.568, 70.689]}>
        <mesh name="Plane343" castShadow={castShadow} geometry={nodes.Plane343.geometry} material={materials.Base} />
        <mesh name="Plane343_1" castShadow={castShadow} geometry={nodes.Plane343_1.geometry} material={materials.Primary} />
        <mesh name="Plane343_2" castShadow={castShadow} geometry={nodes.Plane343_2.geometry} material={glass} />
      </group>
      <group name="Store008" position={[68.56, 0.568, 43.491]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh name="Plane355" castShadow={castShadow} geometry={nodes.Plane355.geometry} material={materials.Primary} />
        <mesh name="Plane355_1" castShadow={castShadow} geometry={nodes.Plane355_1.geometry} material={materials.Base} />
        <mesh name="Plane355_2" castShadow={castShadow} geometry={nodes.Plane355_2.geometry} material={glass} />
      </group>
      <group name="Store009" position={[47.421, 0.568, 49.954]}>
        <mesh name="Plane355" castShadow={castShadow} geometry={nodes.Plane355.geometry} material={materials.Primary} />
        <mesh name="Plane355_1" castShadow={castShadow} geometry={nodes.Plane355_1.geometry} material={materials.Base} />
        <mesh name="Plane355_2" castShadow={castShadow} geometry={nodes.Plane355_2.geometry} material={glass} />
      </group>
      <group name="Gas_Station" position={[53.491, 0.744, 49.546]} scale={[0.77, 0.77, 0.609]}>
        <mesh name="Plane356" castShadow={castShadow} geometry={nodes.Plane356.geometry} material={materials.Base} />
        <mesh name="Plane356_1" castShadow={castShadow} geometry={nodes.Plane356_1.geometry} material={glass} />
      </group>
      <group name="store_M001" position={[35.971, 0.568, 60.533]} rotation={[Math.PI, 0, Math.PI]} scale={1.702}>
        <mesh name="Cube009" castShadow={castShadow} geometry={nodes.Cube009.geometry} material={materials.Base} />
        <mesh name="Cube009_1" castShadow={castShadow} geometry={nodes.Cube009_1.geometry} material={materials.Primary} />
        <mesh name="Cube009_2" castShadow={castShadow} geometry={nodes.Cube009_2.geometry} material={glass} />
      </group>
      <group name="store_S003" position={[59.043, 1.484, 46.561]} rotation={[0, Math.PI / 2, 0]} scale={1.829}>
        <mesh name="Cube010" castShadow={castShadow} geometry={nodes.Cube010.geometry} material={materials.Primary} />
        <mesh name="Cube010_1" castShadow={castShadow} geometry={nodes.Cube010_1.geometry} material={materials.Base} />
      </group>
      <group name="Stand" position={[18.512, 0.862, 48.493]}>
        <mesh name="Plane049" castShadow={castShadow} geometry={nodes.Plane049.geometry} material={materials.Primary} />
        <mesh name="Plane049_1" castShadow={castShadow} geometry={nodes.Plane049_1.geometry} material={materials.Base} />
      </group>
      <group name="Stand008" position={[13.386, 0.862, 48.536]}>
        <mesh name="Plane049" castShadow={castShadow} geometry={nodes.Plane049.geometry} material={materials.Primary} />
        <mesh name="Plane049_1" castShadow={castShadow} geometry={nodes.Plane049_1.geometry} material={materials.Base} />
      </group>
      <mesh name="Stand001" castShadow={castShadow} geometry={nodes.Stand001.geometry} material={materials.Base} position={[18.518, 0.862, 50.613]} />
      <mesh name="Stand002" castShadow={castShadow} geometry={nodes.Stand002.geometry} material={materials.Base} position={[13.355, 0.862, 50.649]} />
      <mesh name="Stand005" castShadow={castShadow} geometry={nodes.Stand005.geometry} material={materials.Base} position={[18.397, 0.862, 42.058]} />
      <mesh name="Stand011" castShadow={castShadow} geometry={nodes.Stand011.geometry} material={materials.Base} position={[15.813, 0.862, 42.139]} />
      <mesh name="Stand003" castShadow={castShadow} geometry={nodes.Stand003.geometry} material={materials.Base} position={[20.448, 0.871, 50.691]} />
      <mesh name="Stand007" castShadow={castShadow} geometry={nodes.Stand007.geometry} material={materials.Base} position={[20.47, 0.871, 48.529]} />
      <mesh name="Stand009" castShadow={castShadow} geometry={nodes.Stand009.geometry} material={materials.Base} position={[16.612, 0.871, 50.638]} />
      <group name="Stand006" position={[20.423, 0.871, 42.11]}>
        <mesh name="Plane048" castShadow={castShadow} geometry={nodes.Plane048.geometry} material={materials.Primary} />
        <mesh name="Plane048_1" castShadow={castShadow} geometry={nodes.Plane048_1.geometry} material={materials.Base} />
      </group>
      <group name="Stand010" position={[15.237, 0.871, 50.585]}>
        <mesh name="Plane048" castShadow={castShadow} geometry={nodes.Plane048.geometry} material={materials.Primary} />
        <mesh name="Plane048_1" castShadow={castShadow} geometry={nodes.Plane048_1.geometry} material={materials.Base} />
      </group>
      <mesh name="Stand012" castShadow={castShadow} geometry={nodes.Stand012.geometry} material={materials.Base} position={[20.448, 0.871, 44.174]} />
      <mesh name="Stand015" castShadow={castShadow} geometry={nodes.Stand015.geometry} material={materials.Base} position={[16.612, 0.871, 44.12]} />
      <mesh name="Stand013" castShadow={castShadow} geometry={nodes.Stand013.geometry} material={materials.Base} position={[18.518, 0.862, 44.096]} />
      <mesh name="Stand014" castShadow={castShadow} geometry={nodes.Stand014.geometry} material={materials.Base} position={[13.355, 0.862, 44.132]} />
      <group name="Stand016" position={[15.237, 0.871, 44.068]}>
        <mesh name="Plane239" castShadow={castShadow} geometry={nodes.Plane239.geometry} material={materials.Primary} />
        <mesh name="Plane239_1" castShadow={castShadow} geometry={nodes.Plane239_1.geometry} material={materials.Base} />
      </group>
      <mesh name="Stand017" castShadow={castShadow} geometry={nodes.Stand017.geometry} material={materials.Base} position={[16.565, 0.871, 48.609]} />
      <group name="Stand018" position={[15.189, 0.871, 48.557]}>
        <mesh name="Plane241" castShadow={castShadow} geometry={nodes.Plane241.geometry} material={materials.Primary} />
        <mesh name="Plane241_1" castShadow={castShadow} geometry={nodes.Plane241_1.geometry} material={materials.Base} />
      </group>
      <group name="Stand019" position={[13.386, 0.862, 42.186]}>
        <mesh name="Plane242" castShadow={castShadow} geometry={nodes.Plane242.geometry} material={materials.Primary} />
        <mesh name="Plane242_1" castShadow={castShadow} geometry={nodes.Plane242_1.geometry} material={materials.Base} />
      </group>
      <mesh name="Stand020" castShadow={castShadow} geometry={nodes.Stand020.geometry} material={materials.Base} position={[18.397, 0.862, 46.179]} />
      <mesh name="Stand022" castShadow={castShadow} geometry={nodes.Stand022.geometry} material={materials.Base} position={[15.813, 0.862, 46.26]} />
      <group name="Stand021" position={[20.423, 0.871, 46.231]}>
        <mesh name="Plane244" castShadow={castShadow} geometry={nodes.Plane244.geometry} material={materials.Primary} />
        <mesh name="Plane244_1" castShadow={castShadow} geometry={nodes.Plane244_1.geometry} material={materials.Base} />
      </group>
      <group name="Stand023" position={[13.386, 0.862, 46.307]}>
        <mesh name="Plane245" castShadow={castShadow} geometry={nodes.Plane245.geometry} material={materials.Primary} />
        <mesh name="Plane245_1" castShadow={castShadow} geometry={nodes.Plane245_1.geometry} material={materials.Base} />
      </group>
      <group name="Gas_Station001" position={[15.194, 0.675, 17.418]} scale={0.561}>
        <mesh name="Plane318" castShadow={castShadow} geometry={nodes.Plane318.geometry} material={glass} />
        <mesh name="Plane318_1" castShadow={castShadow} geometry={nodes.Plane318_1.geometry} material={materials.Base} />
        <mesh name="Plane318_2" castShadow={castShadow} geometry={nodes.Plane318_2.geometry} material={materials.Primary} />
      </group>
      <group name="Store002" position={[19.352, 0.568, 17.426]} scale={0.611}>
        <mesh name="Plane160" castShadow={castShadow} geometry={nodes.Plane160.geometry} material={glass} />
        <mesh name="Plane160_1" castShadow={castShadow} geometry={nodes.Plane160_1.geometry} material={materials.Base} />
      </group>
      <group name="Store" position={[3.774, 0.568, -23.958]} rotation={[0, Math.PI / 2, 0]} scale={0.75}>
        <mesh name="Plane141" castShadow={castShadow} geometry={nodes.Plane141.geometry} material={materials.Base} />
        <mesh name="Plane141_1" castShadow={castShadow} geometry={nodes.Plane141_1.geometry} material={glass} />
      </group>
      <group name="Store001" position={[3.774, 0.568, -17.371]} rotation={[0, Math.PI / 2, 0]} scale={0.75}>
        <mesh name="Plane148" castShadow={castShadow} geometry={nodes.Plane148.geometry} material={materials.Base} />
        <mesh name="Plane148_1" castShadow={castShadow} geometry={nodes.Plane148_1.geometry} material={glass} />
      </group>
      <group name="Store003" position={[3.829, 0.568, -14.092]} rotation={[0, Math.PI / 2, 0]} scale={0.611}>
        <mesh name="Plane150" castShadow={castShadow} geometry={nodes.Plane150.geometry} material={glass} />
        <mesh name="Plane150_1" castShadow={castShadow} geometry={nodes.Plane150_1.geometry} material={materials.Base} />
      </group>
      <group name="store_L005" position={[10.741, 0.5, 11.587]} rotation={[Math.PI, 0, Math.PI]} scale={1.971}>
        <mesh name="Text002" castShadow={castShadow} geometry={nodes.Text002.geometry} material={materials.Base} />
        <mesh name="Text002_1" castShadow={castShadow} geometry={nodes.Text002_1.geometry} material={materials.Primary} />
        <mesh name="Text002_2" castShadow={castShadow} geometry={nodes.Text002_2.geometry} material={glass} />
      </group>
      <group name="store_M002" position={[-3.232, 0.5, 11.279]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="Cube008" castShadow={castShadow} geometry={nodes.Cube008.geometry} material={materials.Base} />
        <mesh name="Cube008_1" castShadow={castShadow} geometry={nodes.Cube008_1.geometry} material={glass} />
        <mesh name="Cube008_2" castShadow={castShadow} geometry={nodes.Cube008_2.geometry} material={materials.Primary} />
      </group>
      <group name="Store004" position={[-4.307, 0.568, -28.121]} rotation={[0, -Math.PI / 2, 0]} scale={0.75}>
        <mesh name="Plane161" castShadow={castShadow} geometry={nodes.Plane161.geometry} material={materials.Base} />
        <mesh name="Plane161_1" castShadow={castShadow} geometry={nodes.Plane161_1.geometry} material={glass} />
      </group>
      <group name="Store005" position={[-4.307, 0.568, -21.534]} rotation={[0, -Math.PI / 2, 0]} scale={0.75}>
        <mesh name="Plane162" castShadow={castShadow} geometry={nodes.Plane162.geometry} material={materials.Base} />
        <mesh name="Plane162_1" castShadow={castShadow} geometry={nodes.Plane162_1.geometry} material={glass} />
      </group>
      <group name="Store006" position={[-4.252, 0.568, -18.255]} rotation={[0, -Math.PI / 2, 0]} scale={0.611}>
        <mesh name="Plane163" castShadow={castShadow} geometry={nodes.Plane163.geometry} material={glass} />
        <mesh name="Plane163_1" castShadow={castShadow} geometry={nodes.Plane163_1.geometry} material={materials.Base} />
      </group>
      <group name="store_L003" position={[-3.906, 0.568, -24.809]} rotation={[0, -Math.PI / 2, 0]} scale={1.118}>
        <mesh name="Text001" castShadow={castShadow} geometry={nodes.Text001.geometry} material={materials.Base} />
        <mesh name="Text001_1" castShadow={castShadow} geometry={nodes.Text001_1.geometry} material={glass} />
        <mesh name="Text001_2" castShadow={castShadow} geometry={nodes.Text001_2.geometry} material={materials.Primary} />
      </group>
      <group name="store_M" position={[-4.344, 1.286, -14.518]} rotation={[0, -Math.PI / 2, 0]} scale={1.413}>
        <mesh name="Cube006" castShadow={castShadow} geometry={nodes.Cube006.geometry} material={materials.Base} />
        <mesh name="Cube006_1" castShadow={castShadow} geometry={nodes.Cube006_1.geometry} material={materials.Primary} />
        <mesh name="Cube006_2" castShadow={castShadow} geometry={nodes.Cube006_2.geometry} material={glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/buildings/Stores.glb')
