/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/car/Truck_001.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Truck_001.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[23.893, 0.594, 22.738]} rotation={[-Math.PI, 0.911, -Math.PI]} scale={1.064}>
        <mesh geometry={nodes.mesh980636007001.geometry} material={materials.Base} />
        <mesh geometry={nodes.mesh980636007001_1.geometry} material={materials.Primary} />
      </group>
    </group>
  )
}

useGLTF.preload('/Truck_001.glb')
